### ISSUE TITLE
Accepting any network string shouldn't happen, you can`t connect without tcp

### ISSUE THREAD

**Issue by RealFruit** [garyburd/redigo#100]
// Dial connects to the Redis server at the given network and address.
func Dial(network, address string) (Conn, error) {
	dialer := xDialer{}
	return dialer.Dial(network, address)
}

...
	dial := d.NetDial
	if dial == nil {
		dial = net.Dial
	}
...

dialer.Dial is net.Dial that can accept tcp,udp,unix etc. but redis wont connect like that, wont it?

**Comment by garyburd** [comment]
An application can connect with "tcp", "unix" and "tcp4" or "tcp6".

**Comment by RealFruit** [comment]
I see your point about tcp, but how would you connect using "unix"?

**Comment by garyburd** [comment]
To connect using a Unix socket, configure Redis to listen on a Unix socket using the unixsocket parameter in redis.conf.  On the client, dial with "unix" and the path specified in redis.conf.

**Comment by RealFruit** [comment]
Thanks :)
