### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by stephane** [garyburd/redigo#103]
Could you tag the tree with a first release number?

**Comment by garyburd** [comment]
What problem will this fix?

**Comment by fjjiaboming** [comment]
I think Stephane say the project management , not source has problem.


On Mon, Jan 26, 2015 at 10:37 PM, Gary Burd <notifications@github.com>
wrote:

> What problem will this fix?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/garyburd/redigo/issues/103#issuecomment-71469476>.
>



-- 
林足雄

QQ:         *534439207 */ fjjiaboming
Email：    linzuxiong1988@gmail.com
Mobile:     *18688162114*
Weibo：   fjjiaboming

**Comment by pbdeuchler** [comment]
I think this is for tools like http://labix.org/gopkg.in

**Comment by garyburd** [comment]
With the exception of a feature that was released and quickly retracted a while ago, Redigo has maintained version compatibility per the guidelines for gopkg.in.  If I do need to create a new version per those guidelines, I will consider publishing the package through gopkg.in. I will not break applications that import the package using the path  "github.com/garyburd/redigo/redis".

@stephane Can you explain the reason why you want the project tagged with a version?

**Comment by fjjiaboming** [comment]
http://gopkg.in

**Comment by garyburd** [comment]
@fjjiaboming What about gopkg.in?

**Comment by fjjiaboming** [comment]
put your project to gopkg.in so that gopher do get it easily .

**Comment by garyburd** [comment]
How is it easier?

**Comment by stephane** [comment]
@garyburd we deploy our Go packages as Debian packages so they require a version number (semantic version). I prefer to use the upstream version number rather than an arbitrary one.
