### ISSUE TITLE
TCP keep-alive

### ISSUE THREAD

**Issue by fjjiaboming** [garyburd/redigo#104]
Please support new features : 
--
* redigo add keep-alived with tcp_keepalive_time , to connect the Redis Server.

#### Manual setting
   The timeout can be manual configured.

**Comment by garyburd** [comment]
You can set keep-alive today:

    tc, err := net.DialTCP("tcp", nil, addr)
    if err != nil {
        // handle error
    }
    if err := tc.SetKeepAlive(true); err != nil {
       // handle error
    }
    if err := tc.SetKeepAlivePeriod(d); err != nil {
      // handle error
   }
   c := redis.NewConn(tc, readTimeout, writeTimeout)

What is the scenario where you need keep-alive?  

Please create a separate issue for pool get blocking timeout. It's easier to track things if there's one feature per issue.

**Comment by fjjiaboming** [comment]
Now I have separated the issues. 
The scenario is that I want keep it always and I will detect the health by myself in Application layer.

**Comment by fjjiaboming** [comment]
Do not want let the net.Conn reconnect again and again.

**Comment by garyburd** [comment]
You can set keep-alive on connections now as shown in my previous comment.  Does that meet your needs?

Setting TCP keep-alive will not prevent the Redis server from timing out an inactive connection.

**Comment by fjjiaboming** [comment]
Yes , it meets my needs. 
>  Setting TCP keep-alive will not prevent the Redis server from timing out an inactive connection.
SetKeepAlivePeriod , is it affects?

**Comment by fjjiaboming** [comment]
Last two days, I have done the stress testing then I found above.
When using Pool.GetResource() , redigo reconnect the Redis-server again and again.
I have an very strict high-performance requirement . We must short the Response-Time for Application Layer. 
The pool , it should not reconnect every time.

> What is the scenario where you need keep-alive?

**Comment by fjjiaboming** [comment]
> What is the scenario where you need keep-alive?
> - dafdsa

**Comment by garyburd** [comment]
The TCP keep-alive time has no impact on when Redigo closes connections.

Are you setting [MaxIdle](http://godoc.org/github.com/garyburd/redigo/redis#Pool.MaxIdle) to a value greater than zero? If it's zero, the pool will reconnect on every call to Get.

**Comment by fjjiaboming** [comment]
My code:
```
func newPool(server, password string) *redis.Pool {
    return &redis.Pool{
        MaxActive:   2,  
        MaxIdle:     1,  
        IdleTimeout: 600 * time.Second,
        Wait:        true,
        Dial: func() (redis.Connection, error) {
            c, err := redis.Dial("tcp", server)
            if err != nil {
                log.Println("Create one connection, a error occurs.", server)
                return nil, err 
            }   
            if password != "" {
                if _, err := c.Do("AUTH", password); err != nil {
                    c.Close()
                    return nil, err 
                }
            }
            return c, err
        },
    }
}
```

**Comment by garyburd** [comment]
To avoid reconnects except on the 600 second idle timeout, set MaxIdle = 2.

**Comment by fjjiaboming** [comment]
And what is the real meaning of MaxActive?

**Comment by garyburd** [comment]
MaxActive specifies the maximum number of server connections that the pool has open at any one time. This count includes idle connections in the pool and connections in use by the application.

MaxIdle specifies the maximum number of idle connections allowed in the pool.

If MaxIdle == MaxActive and Wait == true, then the pool does not close database connections except on timeout.

**Comment by garyburd** [comment]
Please reopen this issue if you can show a scenario where TCP keepalive helps. You can experiment with keepalive using the code in one of my previous comments.
