### ISSUE TITLE
Blocking with timeout when Get PooledConn

### ISSUE THREAD

**Issue by ghost** [garyburd/redigo#105]
## Please support new features : 
- We need blocking with timeout when Pool.Get() return PooledConn.
#### Manual setting

   The timeout can be manual configured.

**Comment by garyburd** [comment]
There are two ways to expose this in the API:

1. Add new Pool field WaitTimeout.  If timeout expires during Get(), then Get returns a connection that returns an error from all methods.
2. Add new Pool method GetWait(timeout time.Duration).

**Comment by fjjiaboming** [comment]
I think the best way is to let user configure  when 
<pre>
    &Pool{
         MaxWait : time
    }
</pre>


You can read the Jedis (Java Project) source .   Java Project,  that on Production , is been audited.

**Comment by fjjiaboming** [comment]
@garyburd   What is help-wanted ?

**Comment by garyburd** [comment]
@fjjiaboming  I am looking for somebody to implement the feature. 

Any contributor should follow [the guidelines in the readme file](https://github.com/garyburd/redigo#contributing).

**Comment by toontong** [comment]
Does it going on ？ I mean Coding or testing? and when Release?

**Comment by jolestar** [comment]
@garyburd  i rewrite the apache commons pool to golang,  redigo can use https://github.com/jolestar/go-commons-pool as connection pool,  can support all configuration option like jedis(jedis use apache commons pool).

**Comment by garyburd** [comment]
Use [third party resource pool](https://godoc.org/?q=resource+pool).  I have no plans to add this feature to Redigo.
