### ISSUE TITLE
How to scan a map

### ISSUE THREAD

**Issue by kostonstyle** [garyburd/redigo#106]
Is it possible to scan a map instead scan struct?

**Comment by garyburd** [comment]
Write a for loop:

    v, err := redis.Strings(c.Do("HGETALL", key))
    if err != nil {
          // handle error
    }
    m := map[string]string  
    for i := 0; i < len(v); i += 2 {
       m[v[i]] = m[v[i+1]]
    }

**Comment by kostonstyle** [comment]
Thanks so much.
