### ISSUE TITLE
Proposal (+code): friendly handling of pipelines/transaction with a Batch object 

### ISSUE THREAD

**Issue by dvirsky** [garyburd/redigo#107]
So, I've been working with pipelines and transactions a bit, and I've created this for my own use, if you're interested I'll put it as a pull request.

The gist of it: There is a `Batch` object that does two things:
1. Automates Send/Receive/Flush and has two main methods: `Send` and `Execute` which does all the rest.
2. It returns "Promises" for each `Send`, that get filled with the return value for each command upon calling `Execute`, making working with return values extremely easy.

Here's the code, I've also written tests and examples. https://gist.github.com/dvirsky/16411e335531aef6c5bf

And an example usage:

``` go

func ExampleBatch() {

    conn, e := redis.Dial("tcp", "localhost:6375")
    if e != nil {
        panic(e)
    }

    // create a new batch from the connection
    b := NewBatch(conn)

    // send a SET command
    if _, e := b.Send("SET", "foo", "BAR"); e != nil {
        panic(e)
    }

    // Send a GET command and keep a promise that will contain its value after execution
    promise, e := b.Send("GET", "foo")
    if e != nil {
        panic(e)
    }

    // execute also returns the promises, but we're not interested in this right now
    if _, e := b.Execute(); e != nil {
        panic(e)
    }

    // extract the returned value from the promise and pass it to redis.String
    s, _ := redis.String(promise.Reply())

    fmt.Println(s)
    // Output: BAR

}

```

**Comment by garyburd** [comment]
I like this proposal. The reason that I've been slow to move on this is that I want to ensure that the design works well with pipelines on Redis cluster. Because I am not using Redis cluster myself, I am not sure that I fully understand the issues.  Ideally somebody gets up to speed on Redigo and cluster and then can comment on this.

**Comment by dvirsky** [comment]
@garyburd the current design will probably not play well with it, as behind the scenes we are using a single connection for the entire pipeline. And cluster doesn't have access nodes IIRC.

AFAIK other redis libraries don't do anything special for this purpose, and I'm not sure what the guidelines for transactions and pipelines are regarding cluster. I'll read a bit about it and see. 

But of course it's no worse than naively doing many `Send` commands over a cluster. 

BTW I've started using this code myself and found some bugs and improved it, so if and when you decide to move forward, I'll make a merge request  with a more up-to-date version of it.

**Comment by garyburd** [comment]
The issue on cluster is that you cannot tell if the command was sent to the correct node until reading the response. I am unsure if nothing should be done about this, a transaction should be used so that the entire batch succeeds or fails, or if commands should be retried.

**Comment by dvirsky** [comment]
Yeah. I read the code of the most popular python client, and it offers no guarantees regarding cluster.

**Comment by garyburd** [comment]
I'd like to combine this idea with a helper for a WATCH/MULTI/EXEC loop.  Here's a rough sketch of what the code will look like:

    var v interface{}
    err := redis.RunTransaction(c, retryCount, func(b *redis.Batch) error {
       b.Start()
       p := b.Send("GET", "key")
       if err := b.Execute(); err != nil {
          return err
      }
      v = p.Value()
      return nil
    } )

RunTransaction reruns the the function up to retryCount times on transaction error return from EXEC.

I am inclined to focus on transactions because transactions are required to reliably pipeline on Redis cluster.

**Comment by dvirsky** [comment]
That's a nice API. 
Do you think a transaction in cluster mode will handle sharding under the hood? or will we leave it to the user to create a transaction consisting of keys that belong in on partition only?

**Comment by garyburd** [comment]
The cluster mode connection will select an underlying connection to a node use key arguments.  This will be transparent when used with the Do method or with the proposed RunInTransaction function above. 

Sharding will not be transparent when using Send and Receive directly.  If the key moved error is returned from Receive, then it's the application's responsibility to retry Send.

**Comment by dvirsky** [comment]
Alright. so this code doesn't really need to be cluster aware. So do you want me to work on my code a bit and add the RunTransaction method to the client?

**Comment by garyburd** [comment]
Yes, please send a PR.

- I think it will be simpler for the application if any error on a call to Send is saved and returned on the call to Execute. 
- I don't like the name Promise because there's no promise that a value will be returned. That said, I cannot think of a better name.

**Comment by dvirsky** [comment]
Re the promise - the other alternative is obviously a Future, but that implies the future/async idiom a-la JS even more than promise does, so I went with promise.

**Comment by garyburd** [comment]
This feature can be added in another package. I am not adding significant new features to Redigo.
