### ISSUE TITLE
goroutine 3391 [IO wait]: net.(*pollDesc).Wait(0xc086351970, 0x77, 0x0, 0x0)

### ISSUE THREAD

**Issue by bbs3723216** [garyburd/redigo#110]
func (this *MainController) Get() {
//	chs := make(chan[21] userBaseUnSer)
	for i:= 0;i<21;i++{
		chs := make(chan userBaseUnSer)
		go listUser(i,chs)
	}
	//fmt.Println(<-chs)
	this.ServeJson()
}
/**
 *
 */
func listUser(i int,c chan userBaseUnSer){
	client := redis.GetRedis()
	defer client.Close()
	v, err := redisparse.Values(client.Do("HGETALL", "users:"+strconv.Itoa(i)))
	if err != nil {
		fmt.Println(err)
	}else if err := redisparse.ScanStruct(v, &userBaseSer); err != nil {
		fmt.Println(err)
	}
	c <- userBaseUnSer{userBaseSer.Username,userBaseSer.Password,userBaseSer.Nickname}
}

**Comment by bbs3723216** [comment]
goroutine coding problem????

**Comment by bit4bit** [comment]
are you using pool of connections?

**Comment by bbs3723216** [comment]
func newPool() *redis.Pool {
	return &redis.Pool{
		MaxIdle: 80,
		MaxActive: 12000, // max number of connections
		Dial: func() (redis.Conn, error) {
			c, err := redis.Dial("tcp", "127.0.0.1:6379")
			if err != nil {
				panic(err.Error())
			}
			return c, err
		},
	}
}
