### ISSUE TITLE
unsupported concurrent read by application

### ISSUE THREAD

**Issue by Hokutosei** [garyburd/redigo#111]
Greetings,

I'm not quite familiar with redigo but, i keep getting this error

    redigo: unexpected response line (possible server error or unsupported concurrent read by application)

how do i prevent this? is there any setting I need to do? thank you!

**Comment by Hokutosei** [comment]
nvm, solved the problem from here. 
http://stackoverflow.com/questions/26344782/getting-response-line-error-redigo-redis-client

**Comment by zhangruiskyline** [comment]
I had same problem if I use one connection per each instance, my redis access is read only, how can read only still have contention error?

**Comment by garyburd** [comment]
@zhangruiskyline The error message describes the problem.  See https://godoc.org/github.com/garyburd/redigo/redis#hdr-Concurrency.  Run your application with the race detector.
