### ISSUE TITLE
Pool for pubsub connections?

### ISSUE THREAD

**Issue by webdev** [garyburd/redigo#114]
I have a very busy system with highly concurrent long poll connections that use pubsub, and it seems like on reconnect the number of connections to Redis goes quite high. Is it possible that it happens because I only use one pubsub connection? Does it make sense to have a pool for pubsub connections?

**Comment by garyburd** [comment]
If you are opening and closing a connection for each long polling request, then it will be helpful to use a pool.

A better option is to use a single pubsub connection for all long polling requests. This requires a simple in-process pubsub system layered over Redis pubsub.

**Comment by webdev** [comment]
No, I only have one connection that I open when the server starts, so I don't open and close it every time.

**Comment by webdev** [comment]
Also, what's the general strategy for the pool size. I have thousands of clients trying to re-connect at the same time, and it feels like I can tweak the size of the pool, but I'm not sure what to set it to.

**Comment by webdev** [comment]
Also, I currently don't have a MaxActive set on my write pool, which probably means that I'm hammering my redis.

**Comment by garyburd** [comment]
If the application uses one connection to the Redis server opened at server start, then I don't understand how the number of connections to the Redis server can go quite high. Can you provide more detail about how your application uses Redigo?

**Comment by webdev** [comment]
Yes, there are few things that are happening.

There are few different connections that the server is currently using:
1. Pubsub (1 connection for all thousands of clients)
2. Write connection pool for writing to the master (heavy writing to Redis for throttling purposes). Every request has an increment counter in Redis, which creates a lot of connections (probably if the pool is too small)?
3. Read connection pool. Every connection to the server does a read operation against read slaves.

Does it make sense?

Thanks.

**Comment by webdev** [comment]
Also I'm running Redis on ElasticCache on AWS, that has a limit of 65K connections, and if connections go higher than 30K, Redis starts doing all kinds of wacky things.

**Comment by garyburd** [comment]
My guess is that one of two things is going on:

- The application gets a connection from the pool and holds it for the duration of a long polling request.  This will create one connection to the Redis server for each active long polling request. It's best to get the connection from the pool, use it and close it without blocking on a long operation. If the long polling handler needs to access Redis at the beginning and end of the request, then it's best to get and close the connection once at the start and once at the end.
- The application is leaking connections. Check to see that the application closes pooled connections.

**Comment by webdev** [comment]
Solved. Thanks. MaxActive did the trick
