### ISSUE TITLE
pool.go bug

### ISSUE THREAD

**Issue by Terry-Mao** [garyburd/redigo#116]
func (p *Pool) put(c Conn, forceClose bool) error {
	err := c.Err()
	p.mu.Lock()
	if !p.closed && err == nil && !forceClose {
		p.idle.PushFront(idleConn{t: nowFunc(), c: c})
		if p.idle.Len() > p.MaxIdle {
			c = p.idle.Remove(p.idle.Back()).(idleConn).c
		} else {
			c = nil
		}
	}

we got a conn from linked-list's front,but put back to the front which means the list's back may have idle timeout conn when concurrency is low but when at a high concurrency, touch the list's back may get a timeout conn.

how about?

func (p *Pool) put(c Conn, forceClose bool) error {
	err := c.Err()
	p.mu.Lock()
	if !p.closed && err == nil && !forceClose {
		p.idle.PushBack(idleConn{t: nowFunc(), c: c})
		if p.idle.Len() > p.MaxIdle {
			c = p.idle.Remove(p.idle.Front()).(idleConn).c
		} else {
			c = nil
		}
	}

let every conn has a chance to got used...

**Comment by felixhao** [comment]
up, I have the same issue.o(^▽^)o

**Comment by Terry-Mao** [comment]
it's fix, my mistake...

**Comment by garyburd** [comment]
The application will see timed out connections if the application does not set the [idle timeout](http://godoc.org/github.com/garyburd/redigo/redis#Pool.IdleTimeout) to a value less than Redis server's connection timeout.  Please check your timeout values and report back.

The pool returns connections to the front of the list as a simple strategy for shrinking the pool after a burst of activity.
