### ISSUE TITLE
Unexpected type for Values, got type []uint8

### ISSUE THREAD

**Issue by bbyler** [garyburd/redigo#118]
This should be an easy issue, just me lacking sleep

I have a key in Redis of the form "sessions:2" pointing to "token": "abc-123" (HASH). Running the following code:

```
func main() {
  reply, err := redis.Values(redis_helper.R.Do("HGET", "sessions:2", "token"))
  if err != nil {
    log.Println("Error: ", err)
    return 
  }
}
```

prints "Unexpected type for Values, got type []uint8".

**Comment by garyburd** [comment]
HGET returns a bulk string. Use redis.String() or rediss.Bytes() to get the bulk string.

**Comment by bbyler** [comment]
Ah, easy. Thanks!
