### ISSUE TITLE
too many arguments in call to conn.Do("Rpush", key, list...)

### ISSUE THREAD

**Issue by AlexLuya** [garyburd/redigo#119]
Hello:
     When I try to rpush multiple items to a list like this:
````go
list:=[]interface{}{"item_1","item_2"}
conn.Do("Rpush", key, list...)
````
it gives me a compilation error:too many arguments in call to conn.Do(...,why?

**Comment by garyburd** [comment]
The Redis command arguments are passed as a single variadic argument to the Do method. The code above is passing two arguments where the one variadic argument is expected.

Here are a couple of ways to call the method.

    c.Do("RPUSH", "key", "item_1", "item_2")

    list:=[]interface{}{"item_1","item_2"}
    c.Do("RPUSH", append([]interface{}{"key"}, list...))

**Comment by vishal24tuniki** [comment]
@garyburd @AlexLuya I found `c.Do("RPUSH", append([]interface{}{"key"}, list...))` also not be working.

According to me, the proper command should be
```
list:=[]interface{}{"item_1","item_2"}
newlist := []interface{}{"key"}, list...)
conn.Do("Rpush", newlist...)
```
