### ISSUE TITLE
Add support for Redis Cluster

### ISSUE THREAD

**Issue by garyburd** [garyburd/redigo#12]
http://redis.io/topics/cluster-spec

See also http://redis.io/topics/partitioning.

**Comment by CpuID** [comment]
This would be nice, definitely.

Either via the [CLUSTER SLOTS](http://redis.io/commands/cluster-slots) cluster state, or just being dumb for now and honor MOVED and ASK redirections. Possibly even a combination of both, spec has some good suggestions of approaches.

**Comment by Cofyc** [comment]
@garyburd Does this library support redis cluster now?

**Comment by CpuID** [comment]
@Cofyc not yet.

**Comment by sybrandy** [comment]
Hello,

Any progress on this?  We're looking to deploy Redis Cluster in our environment, so it would be nice if this supported it.

Thanks.

**Comment by garyburd** [comment]
Nobody has stepped up to do this work.

**Comment by mindscratch** [comment]
FWIW the [go-redis/redis](https://github.com/go-redis/redis) client supports Redis Cluster.

**Comment by chasex** [comment]
@Cofyc @sybrandy I implement a redis cluster client based on Redigo, take a look at [redis-go-cluster](https://github.com/chasex/redis-go-cluster).

**Comment by zalecn** [comment]
I push a simple cluster implement. please have a look, and give same suggestions, thanks.
#170

**Comment by AirJay** [comment]
Hi，garyburd
Is there any specific plan to support for redis cluster?
We're investigating redis cluster and preparing to deploy it in our prod env.
A redis client for go which supports cluster commands (create cluster, add node, del node, reshard, cluster state) will be very useful for us.

Thanks.

**Comment by garyburd** [comment]
@AirJay I am looking for a new maintainer for the project. I don't know if the new maintainer will add support for cluster.

**Comment by garyburd** [comment]
I have no plans to add this feature.  See the [related projects list](https://github.com/garyburd/redigo#related-projects) for cluster implementations.
