### ISSUE TITLE
Trying to build app with GAE

### ISSUE THREAD

**Issue by mblasi** [garyburd/redigo#122]
Hi! I just started a go-martini app, and it is using this module.
It worked as expected when running it by 'go run...'
Unfortunatly, I get this error while trying to build the application for google app engine:

go-app-builder: Failed parsing input: package "src/github.com/garyburd/redigo/redis" cannot import internal package "github.com/garyburd/redigo/internal"

As far as I found in google, it is not recommended to import internal packages, isn't it?

Bests regards,
Matías.

**Comment by garyburd** [comment]
Applications communicate with a Redis server using a TCP socket.  If you have not already done so, read the restrictions on using sockets on App Engine at https://cloud.google.com/appengine/docs/go/sockets/.

There's nothing wrong with using the internal package feature in the go tool.

I cannot reproduce the build issue. Can you provide more information about your environment:

- GOPATH as reported by `goapp env`
- How you installed goapp. There are at least two ways to install goapp.  They may not be the same.
- Absolute path of the package github.com/garyburd/redigo/redis.
- Absolute path of the directory containing app.yaml.

**Comment by mblasi** [comment]
I'm not deploying into GAE yet.
I'm just trying to run the application localy:

$ gcloud preview app run app.yml
Module [default] found in file [/home/matias/sandbox/factoridea/app.yml]
INFO     2015-05-07 12:40:12,220 devappserver2.py:745] Skipping SDK update check.
WARNING  2015-05-07 12:40:27,266 simple_search_stub.py:1126] Could not read search indexes from /tmp/appengine.factor-idea.matias/search_indexes
INFO     2015-05-07 12:40:27,267 api_server.py:190] Starting API server at: http://localhost:47005
INFO     2015-05-07 12:40:27,507 dispatcher.py:192] Starting module "default" running at: http://localhost:8080
INFO     2015-05-07 12:40:27,508 admin_server.py:118] Starting admin server at: http://localhost:8000
ERROR    2015-05-07 12:40:29,037 go_runtime.py:171] Failed to build Go application: (Executed command: /home/matias/google-cloud-sdk/platform/google_appengine/goroot/bin/go-app-builder -app_base /home/matias/sandbox/factoridea -arch 6 -dynamic -goroot .....
...
...

2015/05/07 09:40:29 go-app-builder: Failed parsing input: package "src/github.com/garyburd/redigo/redisx" cannot import internal package "github.com/garyburd/redigo/internal"


That is the result.
I installed gcloud following instructions from: https://cloud.google.com/sdk/#Quick_Start

I'm not seting GOPATH for running "gcloud preview app run app.yml" (I just follow the tutorial)

Thank you.

**Comment by garyburd** [comment]
The `gcloud preview app run app.yml` command is new to me.  I installed glcoud per the quick start instructions and can successfully run an app with GOPATH set to a workspace containing Redigo.

As far as I know GOPATH must be set.  Which tutorial are you following?

**Comment by mblasi** [comment]
I tried by setting GOPATH, and I get the same error.
Remember I'm trying to launch a go-martini-app (as far as I know martini uses redigo)
My just started app runs fine with 'go run' command.
The tutorial I'm following is https://cloud.google.com/sdk/gcloud-app

Any other clue?

**Comment by garyburd** [comment]
If Redigo is in your application directory, then remove it. Use GOPATH to pick up the Redigo dependency. I don't have any clues beyond that.

I don't know much about Martini, but it seems unlikely that Martini was written to use Redigo with the App Engine restrictions on sockets.  You might want to check if Martini works with Redigo in the App Engine environment before pursuing this configuration issue.

**Comment by garyburd** [comment]
I skimmed the error messages message above and noticed that the application uses the redisx package. Are you really using this experimental and unsupported package?

**Comment by mblasi** [comment]
I'm just using go-martini, I don't know why redisx is there, go dependency resolution should be who retrieve it.
redis path: /home/matias/sandbox/myapp/src/github.com/garyburd/redigo/redis
app.yaml: /home/matias/sandbox/myapp/

Regards,
Matías.

**Comment by garyburd** [comment]
Remove Redigo from your application directory. Install Redigo in a Go workspace and let the App Engine tools find Redigo using GOPATH.

I looked at Martini and found that it does not [depend on Redigo](http://godoc.org/github.com/go-martini/martini?imports). Removing Redigo from your application might be sufficient to solve this problem.
