### ISSUE TITLE
Is .Flush() guaranteed to write data to Redis when it was executed?

### ISSUE THREAD

**Issue by arianitu** [garyburd/redigo#125]
I'm trying to send a huge batch of LPUSH and EXPIREs to Redis and I don't care about the reply. The problem is, after I SEND and FLUSH all my commands and close the connections, some commands don't get commited on the Redis side (even though I flushed them.) These are usually the last few thousand 

Here is the majority of the code that does this:

```
type Command struct {
	Name string
	Values []interface{}
	Expire time.Duration
}

in := make(chan Command)
sink := make(chan int)
wg := sync.WaitGroup{}
go func () {
	for _ = range sink {
		wg.Done()
	}
}()

func Worker(client redis.Conn, in chan Command, sink chan int) {
	for command := range in {
		err := client.Send(command.Name, command.Values...)
		checkError(err)
		if command.Expire.Seconds() > 0 {
			err = client.Send("EXPIRE", command.Values[0], strconv.Itoa(int(command.Expire.Seconds())))
			checkError(err)
		}
		err = client.Flush()
		checkError(err)
		sink <- 1
	}
}

for i := 0; i < 350; i++ {
    client, err := redis.Dial("tcp", ":6379")
    checkError(err)
    defer client.Close()
    go Worker(client, in, sink)
}

for i := 0; i < 100000; i++ {
    for n := 0; n < 400; n++ {
        wg.Add(1)
        in <- Command{Name: "LPUSH", Values: []interface{} {"inbox:" + strconv.Itoa(i), "hello"}, Expire: 30 * (24 * time.Hour)}
    }
}
wg.Wait()

```

If I switch to .Do() instead of .Send(), the program is about 10x slower as it has to wait for every reply. 

So I guess my question is.. is there a way to use pipelining to send a huge batch of commands, ignore the results, and know when it's completed?

**Comment by arianitu** [comment]
I think I should probably do this in batches since replies are queued in memory and will have a decent overhead for 40 million commands.

I'm going to attempt 10k sends/10k receives, that might be faster than using .Do()

**Comment by alex179ohm** [comment]
Flush() is just a wrapper around a [bufio (Writer).Flush()](http://golang.org/pkg/bufio/#Writer.Flush) which writes buffered data in the underlying io.Writer (more specifically a net.Conn.Writer), Flush() just guarantee data is being written on (redis) socket (or not if fail).
There is not a delay on sending data, so Flush(), if not fail, guarantee the buffer socket has been written and redis have received the data sent from it.
In fact the same [Do() check the return of Flush()](https://github.com/garyburd/redigo/blob/master/redis/conn.go#L419) before starts on reading the response from redis.

**Comment by garyburd** [comment]
Thank you @alex179ohm for the answer.

**Comment by arianitu** [comment]
@garyburd What do you mean there isn't a guarantee that the server reads the data? 

Here's a repo case:

```
package main

import (
	"github.com/garyburd/redigo/redis"
	"strconv"
	"time"
	"sync"
	"runtime"
)

type Command struct {
    Name string
    Values []interface{}
    Expire time.Duration
}


func checkError(err error) {
	if err != nil {
		panic(err)
	}
}

func Worker(client redis.Conn, in chan Command, sink chan int) {
    for command := range in {
        err := client.Send(command.Name, command.Values...)
        checkError(err)
        if command.Expire.Seconds() > 0 {
            err = client.Send("EXPIRE", command.Values[0], strconv.Itoa(int(command.Expire.Seconds())))
            checkError(err)
        }
        err = client.Flush()
        checkError(err)
        sink <- 1
    }
}

func main() {
	runtime.GOMAXPROCS(runtime.NumCPU())
	
	in := make(chan Command)
	sink := make(chan int)
	wg := sync.WaitGroup{}
	go func () {
		for _ = range sink {
			wg.Done()
		}
	}()

	for i := 0; i < 350; i++ {
		client, err := redis.Dial("tcp", ":6379")
		checkError(err)
		defer client.Close()
		go Worker(client, in, sink)
	}

	for i := 0; i < 1000; i++ {
		for n := 0; n < 400; n++ {
			wg.Add(1)
			in <- Command{Name: "LPUSH", Values: []interface{} {"inbox:" + strconv.Itoa(i), "hello"}, Expire: 30 * (24 * time.Hour)}
		}
	}
	wg.Wait()
}
```

If you do ```LRANGE "inbox:900" 0 -1``` you can see that the last entries don't have 400 entries, but only around 80. 

Is this just normal redis behaviour if you don't call RECEIVE() before closing connections, or is this an issue with the client library?

**Comment by garyburd** [comment]
The Redis server stops reading commands from a client connection when it encounters an error writing to the client connection.  

If you client application closes the connection with commands in flight, there's no guarantee that the Redis server will read all commands before encountering an error writing a command response.

Applications should receive responses to prevent the server output buffers from growing. See the [Redis documentation on buffer limits](http://redis.io/topics/clients#output-buffers-limits) for more info.

**Comment by garyburd** [comment]
You might find this application helpful.  It pipelines commands to the server with a maximum of 1000 commands in flight. 

    package main

    import (
        "strconv"
        "github.com/garyburd/redigo/redis"
    )

    func checkError(err error) {
        if err != nil {
            panic(err)
        }
    }

    func main() {
        resp := make(chan struct{}, 1000)
        done := make(chan struct{})

        c, err := redis.Dial("tcp", ":6379")
        checkError(err)
        defer c.Close()

        go func() {
            for _ = range resp {
                _, err := c.Receive()
                checkError(err)
            }
            close(done)
        }()

        for i := 0; i < 1000; i++ {
            for n := 0; n < 400; n++ {
                key := "inbox:" + strconv.Itoa(i)
                err := c.Send("LPUSH", key, "hello")
                checkError(err)
                err = c.Send("EXPIRE", key, 30*24*60*60)
                checkError(err)
                err = c.Flush()
                checkError(err)
                // Send signal to response reader after Flush to avoid deadlock.
                resp <- struct{}{}
                resp <- struct{}{}
            }
        }
        close(resp)
        <-done
    }
