### ISSUE TITLE
redis pool connect error  

### ISSUE THREAD

**Issue by ablegao** [garyburd/redigo#130]
my code:

     	client := aorm.Pool.Get()
	defer client.Close()
	mykeys := []string{}
	key := "nadostory:" + strconv.Itoa(int(self.Uid)) + ":*"

	if keys, err := redis.Strings(client.Do("KEYS", key)); err == nil && len(keys) > 0 {
		for _, k := range keys {
			mykeys = append(mykeys, k)
		}
	}

error:

panic: runtime error: slice bounds out of range

goroutine 14 [running]:
bufio.(*Reader).ReadSlice(0xc20825cf60, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/godev/src/bufio/bufio.go:273 +0x266
github.com/garyburd/redigo/redis.(*conn).readLine(0xc2082fa140, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/gao/code/mygo/src/github.com/garyburd/redigo/redis/conn.go:228 +0x6d
github.com/garyburd/redigo/redis.(*conn).readReply(0xc2082fa140, 0x0, 0x0, 0x0, 0x0)
	/Users/gao/code/mygo/src/github.com/garyburd/redigo/redis/conn.go:301 +0x66
github.com/garyburd/redigo/redis.(*conn).Do(0xc2082fa140, 0xa6bb50, 0x4, 0xc2080f8300, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
	/Users/gao/code/mygo/src/github.com/garyburd/redigo/redis/conn.go:447 +0x5c6
github.com/garyburd/redigo/redis.(*pooledConnection).Do(0xc2082776a0, 0xa6bb50, 0x4, 0xc2080f8300, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
	/Users/gao/code/mygo/src/github.com/garyburd/redigo/redis/pool.go:365 +0xf0
nado/userlib.UserApiInfo.Exit(0x7f5f7a96dbb0, 0xc208299e60, 0x0, 0x0, 0x0, 0x0, 0x0, 0xab54f0, 0x9, 0xc208299240, ...)
	/Users/gao/code/mygo/src/nado/userlib/struct_user_api.go:680 +0x278
nado/room.UserClosedToBc(0x7f5f7a971aa0, 0xc2081f44d0, 0x10002, 0x14e4d4df1ab, 0x303ec000a, 0x275c, 0xc2082806c0, 0xe, 0x11, 0xc2082987c0, ...)
	/Users/gao/code/mygo/src/nado/room/processing_of_user_closed.go:52 +0x1354

**Comment by garyburd** [comment]
In the past when this error has come up, the application was accessing a single connection from multiple goroutines.  Is that all of the code that uses the connection?

**Comment by ablegao** [comment]
dear garyburd

This' my connect code: 

	var Pool *redis.Pool = nil
	Pool = &redis.Pool{
		MaxIdle:     50,                //最大的空闲连接数，表示即使没有redis连接时依然可以保持N个空闲的连接，而不被清除，随时处于待命状态。
		MaxActive:   10240,             //最大的激活连接数，表示同时最多有N个连接
		IdleTimeout: 180 * time.Second, //最大的空闲连接等待时间，超过此时间后，空闲连接将被关闭
		Dial: func() (redis.Conn, error) {
			c, err := redis.Dial("tcp", REDIS_HOST)
			if err != nil {
				return nil, err
			}
			if PASSWD != "" && len(PASSWD) > 0 {
				if _, err := c.Do("AUTH", PASSWD); err != nil {
					c.Close()
					return nil, err
				}
			}
			// 选择db
			c.Do("SELECT", cache_db)
			return c, nil
		},
	}



the Pool is global variable ,  i use NSQ manage my message . max goroutines  10240 . In each of the message , Pool.Get a conn , and close this after end.    For the long time, everybody happy . but .




	if aorm.Pool == nil {
		Log.Error("orm.pool is  nil ")
		return
	}
	client := aorm.Pool.Get()
	defer client.Close()
	mykeys := []string{}
	key := "nadostory:" + strconv.Itoa(int(self.Uid)) + ":*"

	if keys, err := redis.Strings(client.Do("KEYS", key)); err == nil && len(keys) > 0 {
		for _, k := range keys {
			mykeys = append(mykeys, k)
		}
	}

	key = "nadouser:" + strconv.Itoa(int(self.Uid)) + ":*"

	if keys, err := redis.Strings(client.Do("KEYS", key)); err == nil && len(keys) > 0 {
		for _, k := range keys {
			mykeys = append(mykeys, k)
		}
	}

	client.Send("MULTI")
	for _, k := range mykeys {
		client.Send("DEL", k)
	}
	client.Send("EXEC")


this' User quit code . In the code , i need delete user data in redis . so  , find the key of User  , and delete keys .
I really want to confirm  , Pool.Get connect run with single goroutine.  

It is strange that , my produce soft is  normal , error occurrend in the development environment . and test user is signle tester. i'm worried ， are we really thinking about potential risks and unintended consequences of progress.

**Comment by ablegao** [comment]
This is a question that is seldom seen

**Comment by garyburd** [comment]
Is this all of the code that uses `aorm.Pool`?

**Comment by LYY** [comment]
@garyburd I have a similar question like that. I have read wiki , docs and codes, the redigo pool still not thread-safe? Can I use it to get a connection in a goroutine?

I recently use https://github.com/jrallison/go-workers, and I want to define a global variable to handle a pool, and then use this pool to get a connection in a goroutine. NOW, I am following the [Vitess-Example](https://github.com/garyburd/redigo/wiki/Vitess-Example). 

I really don't know the difference between redigo's pool and vitess pool.

**Comment by garyburd** [comment]
@LYY  Barring any bugs, the Redigo pool is thread-safe. The pool is designed to be used by multiple goroutines.  The connections returned by the pool are not thread-safe. 

Please post the stack traces that you have seen.

**Comment by garyburd** [comment]
@ablegao Your application is accessing a single connection concurrently.  This can be a result of a bug in the pool or the application.  Please run your application with the [race detector](https://golang.org/doc/articles/race_detector.html) and let me know the results.

**Comment by LYY** [comment]
@garyburd Thank you very much. I'll test my project soon.

**Comment by ablegao** [comment]
==================
WARNING: DATA RACE
Write by goroutine 12:
  syscall.raceWriteRange()
      /opt/godev/src/syscall/race.go:29 +0x40
  syscall.Read()
      /opt/godev/src/syscall/syscall_unix.go:139 +0xa4
  net.(*netFD).Read()
      /opt/godev/src/net/fd_unix.go:238 +0x3b7
  net.(*conn).Read()
      /opt/godev/src/net/net.go:121 +0x124
  net.(*TCPConn).Read()
      <autogenerated>:36 +0x85
  bufio.(*Reader).fill()
      /opt/godev/src/bufio/bufio.go:97 +0x381
  bufio.(*Reader).ReadSlice()
      /opt/godev/src/bufio/bufio.go:295 +0x60b
  github.com/garyburd/redigo/redis.(*conn).readLine()
      /Users/gao/code/mygo/src/github.com/garyburd/redigo/redis/conn.go:228 +0x93
  github.com/garyburd/redigo/redis.(*conn).readReply()
      /Users/gao/code/mygo/src/github.com/garyburd/redigo/redis/conn.go:301 +0x76
  github.com/garyburd/redigo/redis.(*conn).Do()
      /Users/gao/code/mygo/src/github.com/garyburd/redigo/redis/conn.go:434 +0x544
  github.com/garyburd/redigo/redis.(*pooledConnection).Close()
      /Users/gao/code/mygo/src/github.com/garyburd/redigo/redis/pool.go:353 +0x4f8
  github.com/server-nado/orm.(*RedisCache).ConnClose()
      /Users/gao/code/mygo/src/github.com/server-nado/orm/cache_driver_redis.go:59 +0x7b
  github.com/server-nado/orm.(*RedisCache).Hset()
      /Users/gao/code/mygo/src/github.com/server-nado/orm/cache_driver_redis.go:96 +0x34e
  github.com/server-nado/orm.(*CacheModule).Set()
      /Users/gao/code/mygo/src/github.com/server-nado/orm/cache.go:267 +0x5e4
  main.actLoadingMessage()
      /Users/gao/code/mygo/src/codmaster/codconsumer/process_user_friends.go:90 +0x1840
  github.com/server-nado/serve.NadoServer.RunHandler()
      /Users/gao/code/mygo/src/github.com/server-nado/serve/nado_server.go:128 +0x2b7
  github.com/server-nado/serve.RunHand()
      /Users/gao/code/mygo/src/github.com/server-nado/serve/handler.go:67 +0x12e
  github.com/server-nado/serve/socket-consumer-handler.func·001()
      /Users/gao/code/mygo/src/github.com/server-nado/serve/socket-consumer-handler/nsq_handler.go:33 +0x2de
  github.com/server-nado/serve.ReadResponseByConnect()
      /Users/gao/code/mygo/src/github.com/server-nado/serve/bytes.go:168 +0x2c4
  github.com/server-nado/serve/socket-consumer-handler.(*NsqHandler).HandleMessage()
      /Users/gao/code/mygo/src/github.com/server-nado/serve/socket-consumer-handler/nsq_handler.go:35 +0x3d1
  github.com/server-nado/go-nsq.(*Consumer).handlerLoop()
      /Users/gao/code/mygo/src/github.com/server-nado/go-nsq/consumer.go:1094 +0x211

Previous read by goroutine 13:
  github.com/garyburd/redigo/redis.(*conn).readReply()
      /Users/gao/code/mygo/src/github.com/garyburd/redigo/redis/conn.go:308 +0x1a2
  github.com/garyburd/redigo/redis.(*conn).Do()
      /Users/gao/code/mygo/src/github.com/garyburd/redigo/redis/conn.go:447 +0x76e
  github.com/garyburd/redigo/redis.(*pooledConnection).Do()
      /Users/gao/code/mygo/src/github.com/garyburd/redigo/redis/pool.go:365 +0x161
  github.com/server-nado/orm.(*RedisCache).Hmset()
      /Users/gao/code/mygo/src/github.com/server-nado/orm/cache_driver_redis.go:108 +0x471
  github.com/server-nado/orm.CacheModule.SaveToCache()
      /Users/gao/code/mygo/src/github.com/server-nado/orm/cache.go:605 +0xa82
  github.com/server-nado/orm.(*CacheModule).Save()
      /Users/gao/code/mygo/src/github.com/server-nado/orm/cache.go:298 +0x2ff
  main.actUserInfo()
      /Users/gao/code/mygo/src/codmaster/codconsumer/process_userinfo.go:66 +0x5b4
  github.com/server-nado/serve.NadoServer.RunHandler()
      /Users/gao/code/mygo/src/github.com/server-nado/serve/nado_server.go:128 +0x2b7
  github.com/server-nado/serve.RunHand()
      /Users/gao/code/mygo/src/github.com/server-nado/serve/handler.go:67 +0x12e
  github.com/server-nado/serve/socket-consumer-handler.func·001()
      /Users/gao/code/mygo/src/github.com/server-nado/serve/socket-consumer-handler/nsq_handler.go:33 +0x2de
  github.com/server-nado/serve.ReadResponseByConnect()
      /Users/gao/code/mygo/src/github.com/server-nado/serve/bytes.go:168 +0x2c4
  github.com/server-nado/serve/socket-consumer-handler.(*NsqHandler).HandleMessage()
      /Users/gao/code/mygo/src/github.com/server-nado/serve/socket-consumer-handler/nsq_handler.go:35 +0x3d1
  github.com/server-nado/go-nsq.(*Consumer).handlerLoop()
      /Users/gao/code/mygo/src/github.com/server-nado/go-nsq/consumer.go:1094 +0x211

Goroutine 12 (running) created at:
  github.com/server-nado/go-nsq.(*Consumer).AddConcurrentHandlers()
      /Users/gao/code/mygo/src/github.com/server-nado/go-nsq/consumer.go:1076 +0x103
  github.com/server-nado/serve/socket-consumer-handler.(*SocketServer).Run()
      /Users/gao/code/mygo/src/github.com/server-nado/serve/socket-consumer-handler/socket_handler.go:55 +0x8bd

Goroutine 13 (running) created at:
  github.com/server-nado/go-nsq.(*Consumer).AddConcurrentHandlers()
      /Users/gao/code/mygo/src/github.com/server-nado/go-nsq/consumer.go:1076 +0x103
  github.com/server-nado/serve/socket-consumer-handler.(*SocketServer).Run()
      /Users/gao/code/mygo/src/github.com/server-nado/serve/socket-consumer-handler/socket_handler.go:55 +0x8bd
==================
==================
WARNING: DATA RACE
Write by goroutine 12:
  syscall.raceWriteRange()
      /opt/godev/src/syscall/race.go:29 +0x40
  syscall.Read()
      /opt/godev/src/syscall/syscall_unix.go:139 +0xa4
  net.(*netFD).Read()
      /opt/godev/src/net/fd_unix.go:238 +0x3b7
  net.(*conn).Read()
      /opt/godev/src/net/net.go:121 +0x124
  net.(*TCPConn).Read()
      <autogenerated>:36 +0x85
  bufio.(*Reader).fill()
      /opt/godev/src/bufio/bufio.go:97 +0x381
  bufio.(*Reader).ReadSlice()
      /opt/godev/src/bufio/bufio.go:295 +0x60b
  github.com/garyburd/redigo/redis.(*conn).readLine()
      /Users/gao/code/mygo/src/github.com/garyburd/redigo/redis/conn.go:228 +0x93
  github.com/garyburd/redigo/redis.(*conn).readReply()
      /Users/gao/code/mygo/src/github.com/garyburd/redigo/redis/conn.go:301 +0x76
  github.com/garyburd/redigo/redis.(*conn).Do()
      /Users/gao/code/mygo/src/github.com/garyburd/redigo/redis/conn.go:434 +0x544
  github.com/garyburd/redigo/redis.(*pooledConnection).Close()
      /Users/gao/code/mygo/src/github.com/garyburd/redigo/redis/pool.go:353 +0x4f8
  github.com/server-nado/orm.(*RedisCache).ConnClose()
      /Users/gao/code/mygo/src/github.com/server-nado/orm/cache_driver_redis.go:59 +0x7b
  github.com/server-nado/orm.(*RedisCache).Hset()
      /Users/gao/code/mygo/src/github.com/server-nado/orm/cache_driver_redis.go:96 +0x34e
  github.com/server-nado/orm.(*CacheModule).Set()
      /Users/gao/code/mygo/src/github.com/server-nado/orm/cache.go:267 +0x5e4
  main.actLoadingMessage()
      /Users/gao/code/mygo/src/codmaster/codconsumer/process_user_friends.go:90 +0x1840
  github.com/server-nado/serve.NadoServer.RunHandler()
      /Users/gao/code/mygo/src/github.com/server-nado/serve/nado_server.go:128 +0x2b7
  github.com/server-nado/serve.RunHand()
      /Users/gao/code/mygo/src/github.com/server-nado/serve/handler.go:67 +0x12e
  github.com/server-nado/serve/socket-consumer-handler.func·001()
      /Users/gao/code/mygo/src/github.com/server-nado/serve/socket-consumer-handler/nsq_handler.go:33 +0x2de
  github.com/server-nado/serve.ReadResponseByConnect()
      /Users/gao/code/mygo/src/github.com/server-nado/serve/bytes.go:168 +0x2c4
  github.com/server-nado/serve/socket-consumer-handler.(*NsqHandler).HandleMessage()
      /Users/gao/code/mygo/src/github.com/server-nado/serve/socket-consumer-handler/nsq_handler.go:35 +0x3d1
  github.com/server-nado/go-nsq.(*Consumer).handlerLoop()
      /Users/gao/code/mygo/src/github.com/server-nado/go-nsq/consumer.go:1094 +0x211

Previous read by goroutine 13:
  runtime.slicebytetostring()
      /opt/godev/src/runtime/string.go:62 +0x0
  github.com/garyburd/redigo/redis.(*conn).readReply()
      /Users/gao/code/mygo/src/github.com/garyburd/redigo/redis/conn.go:318 +0xbbb
  github.com/garyburd/redigo/redis.(*conn).Do()
      /Users/gao/code/mygo/src/github.com/garyburd/redigo/redis/conn.go:447 +0x76e
  github.com/garyburd/redigo/redis.(*pooledConnection).Do()
      /Users/gao/code/mygo/src/github.com/garyburd/redigo/redis/pool.go:365 +0x161
  github.com/server-nado/orm.(*RedisCache).Hmset()
      /Users/gao/code/mygo/src/github.com/server-nado/orm/cache_driver_redis.go:108 +0x471
  github.com/server-nado/orm.CacheModule.SaveToCache()
      /Users/gao/code/mygo/src/github.com/server-nado/orm/cache.go:605 +0xa82
  github.com/server-nado/orm.(*CacheModule).Save()
      /Users/gao/code/mygo/src/github.com/server-nado/orm/cache.go:298 +0x2ff
  main.actUserInfo()
      /Users/gao/code/mygo/src/codmaster/codconsumer/process_userinfo.go:66 +0x5b4
  github.com/server-nado/serve.NadoServer.RunHandler()
      /Users/gao/code/mygo/src/github.com/server-nado/serve/nado_server.go:128 +0x2b7
  github.com/server-nado/serve.RunHand()
      /Users/gao/code/mygo/src/github.com/server-nado/serve/handler.go:67 +0x12e
  github.com/server-nado/serve/socket-consumer-handler.func·001()
      /Users/gao/code/mygo/src/github.com/server-nado/serve/socket-consumer-handler/nsq_handler.go:33 +0x2de
  github.com/server-nado/serve.ReadResponseByConnect()
      /Users/gao/code/mygo/src/github.com/server-nado/serve/bytes.go:168 +0x2c4
  github.com/server-nado/serve/socket-consumer-handler.(*NsqHandler).HandleMessage()
      /Users/gao/code/mygo/src/github.com/server-nado/serve/socket-consumer-handler/nsq_handler.go:35 +0x3d1
  github.com/server-nado/go-nsq.(*Consumer).handlerLoop()
      /Users/gao/code/mygo/src/github.com/server-nado/go-nsq/consumer.go:1094 +0x211

Goroutine 12 (running) created at:
  github.com/server-nado/go-nsq.(*Consumer).AddConcurrentHandlers()
      /Users/gao/code/mygo/src/github.com/server-nado/go-nsq/consumer.go:1076 +0x103
  github.com/server-nado/serve/socket-consumer-handler.(*SocketServer).Run()
      /Users/gao/code/mygo/src/github.com/server-nado/serve/socket-consumer-handler/socket_handler.go:55 +0x8bd

Goroutine 13 (running) created at:
  github.com/server-nado/go-nsq.(*Consumer).AddConcurrentHandlers()
      /Users/gao/code/mygo/src/github.com/server-nado/go-nsq/consumer.go:1076 +0x103
  github.com/server-nado/serve/socket-consumer-handler.(*SocketServer).Run()
      /Users/gao/code/mygo/src/github.com/server-nado/serve/socket-consumer-handler/socket_handler.go:55 +0x8bd
==================
