### ISSUE TITLE
Connecting via a unix socket

### ISSUE THREAD

**Issue by alexanderbaran** [garyburd/redigo#133]
Is there a possibility of connecting to redis via unix socket instead of tcp? If not, will this feature be implemented? Perhaps it could improve performance.

**Comment by garyburd** [comment]
To open a connection with a Unix socket, [dial](http://godoc.org/net#DialUnix) the Unix connection and pass the result to [redis.NewConn](http://godoc.org/github.com/garyburd/redigo/redis#NewConn).
