### ISSUE TITLE
Support for `redis://` URL format?

### ISSUE THREAD

**Issue by shosti** [garyburd/redigo#134]
Hi, sorry if this has been brought up before or if there's already a solution I'm not aware of. Heroku uses a `REDIS_URL` environment variable of the form `redis://h:<password>@<address>:<port>` to handle connections, which `redis.Dial` does not handle natively. (The `redis://` scheme works for [the official ruby client](https://github.com/redis/redis-rb/blob/master/lib/redis/client.rb#L394) and clients for several other languages.) It's easy enough to extract the password and address with a regexp, but I was wondering if you might consider adding native handling of `redis://` URLs in redigo? (I'd be happy to add this if you're open to it.)

**Comment by garyburd** [comment]
Proposed IANA scheme: https://groups.google.com/d/msg/redis-db/elyRy9KDRtI/uLytz_xT3cgJ

**Comment by shosti** [comment]
Awesome, didn't know about that. I'd be happy to put together something implementing the spec if it makes sense to you. I could think of a couple ways to do the API: either a version of `Dial` that takes a `*url.URL` (maybe `DialURL` or something like that), expecting the user to parse the actual query string, or a version of `Dial` that takes a raw string and does the parsing itself. Thoughts? (I'm fairly new to Go, so I don't have a great sense yet of the most idiomatic way to implement these kinds of APIs.)

**Comment by garyburd** [comment]
I want to export the [Dialer](https://gburd.smugmug.com/Private/2105-07-EL/n-Xvfmv4/) type (by removing the leading 'x') and change it to take a Redis URL instead of a network & address.
