### ISSUE TITLE
Issue opening large number of connections

### ISSUE THREAD

**Issue by sebastianmarkow** [garyburd/redigo#135]
Since Go 1.5.x is using `runtime.NumCPU()` to set the amount of system threads to run goroutines in parallel, pooling & dispatching a large number of calls concurrently will end up in corrupt connections.

System usage limits (usually set via `ulimit` on *nix) are not the source of error.

Code snippet below. If you are on a stable release of go 1.4.x set local env `GOMAXPROCS` to n > 1 to reproduce.

~~~go
package main

import (
    "fmt"
    "log"
    "sync"
    "time"

    "github.com/garyburd/redigo/redis"
)

func main() {
    var wg sync.WaitGroup
    num := 1000

    for i := 0; i < num; i++ {
        wg.Add(1)
        go func(i int) {
            defer wg.Done()
            c, err := redis.DialTimeout("tcp", ":6379", 0, 1*time.Second, 1*time.Second)
            if err != nil {
                log.Println(i, "dial", err)
                return
            }
            defer c.Close()
            if _, err := c.Do("PING"); err != nil {
                fmt.Println(i, "ping", err)
            }
        }(i)
    }
    wg.Wait()
}
~~~

**Comment by garyburd** [comment]
This program produces the same error:

    package main

    import (
        "log"
        "net"
        "sync"
    )

    func main() {
        var wg sync.WaitGroup
        num := 1000

        for i := 0; i < num; i++ {
            wg.Add(1)
            go func(i int) {
                defer wg.Done()
                c, err := net.Dial("tcp", ":6379")
                if err != nil {
                    log.Println(i, "dial", err)
                    return
                }
                defer c.Close()
                var buf [1]byte
                _, err = c.Read(buf[:])
                if err != nil {
                    log.Println(i, "read", err)
                    return
                }
            }(i)
        }
        wg.Wait()
    }

The problem is not with Redigo.

Does this issue occur in a real application?  Typical applications do not open more than 100 connections to the Redis server.

**Comment by ErikDubbelboer** [comment]
I'm curious, what error are you guys seeing? On both 1.4 and 1.5 and with different values for `GOMAXPROCS` I'm never seeing any errors?

**Comment by garyburd** [comment]
Both programs above run without error on Linux.  

@sebastianmarkow What operating system are you running on?

**Comment by garyburd** [comment]
@ErikDubbelboer The error on OS X is:

    2015/08/08 07:01:41 982 dial dial tcp :6379: getsockopt: connection refused

**Comment by gunjan5** [comment]
I get the same error with a simpler code on both Mac OS X 10.9.5 and Ubuntu 14.04 (both with golang version **1.5rc1**), although I don't think it's a Redigo issue. However I'm curious to know if someone figured out the solution. 

```go
panic: dial tcp :6379: getsockopt: connection refused

goroutine 1 [running]:
main.main()
	/desktop/go30days-challenge/day12-redis/redis.go:13 +0xa3

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
exit status 2
```

and the code is:

```go
package main

import (
	"fmt"
	"github.com/garyburd/redigo/redis"
)

func main() {
	c, err := redis.Dial("tcp", ":6379")

	if err != nil {
		panic(err)
	}
	defer c.Close()

	c.Do("SET", "message1", "hello humans!")

	world, err := redis.String(c.Do("GET", "message1"))
	if err != nil {
		fmt.Println("key not found yo")
		panic(err)
	}

	fmt.Println(world)
}
```

I was following this tutorial: https://sendgrid.com/blog/get-going-go-redis/

**Comment by garyburd** [comment]
This does not appear to be an issue with Redigo. Reopen if you can provide more information about the system you are running this on.
