### ISSUE TITLE
ScanStruct can't convert from []uint8 to []int

### ISSUE THREAD

**Issue by tortuoise** [garyburd/redigo#144]
Tried to use ScanStruct with a simple struct like this:

    var s1, s2, struct {
        Intslice []int `redis:"ints"`
    }
    s1.Intslice = []int{1,2,3,4}
    if _,err := c.Do("HMSET", redis.Args{}.Add()("1").AddFlat(&s1)...); err != nil {
        handle(err)
    }
    v, err := redis.Values(c.Do("HGETALL", "1")
    handle(err)
    err = redis.ScanStruct(v, &s2)

ScanStruct throws an error - it can't convert from []uint8 to []int.  Above code works if Intslice is []uint8. Does this require a fix or am I missing something ?

**Comment by garyburd** [comment]
The error is telling you that Redigo cannot convert a Redis bulk string (represented as []uint8 by Redigo) to a slice of integers. I'll improve the error message.

Redigo does not handle nested values. Use JSON, gob or some other encoding to encode and decode nested values to a []byte and store the []byte value.

**Comment by tortuoise** [comment]
Thanks I get it. I was able to marshal the struct into json, store it as []byte, retrieve and unmarshal back into the struct. Is this something worth including as a feature in redigo ? What would be the difficulty or arguments against adding this feature ?

**Comment by garyburd** [comment]
There are many ways to encode values to []byte. It's best left to the application.
