### ISSUE TITLE
execute lua script problem

### ISSUE THREAD

**Issue by huoshiqiu** [garyburd/redigo#146]
i have already load the lua script in redis-cli and get the sha string in order to not load every time when i call redis in go. 

i have look up the  [SendHash()] (https://github.com/garyburd/redigo/blob/3e4727f0ef5938d3a846cdb57e560dba4419e854/redis/script.go) method

But i can not find the way to execute the **EVALSHA** command with this package.

i try to run this:
```go
type Script struct {
	keyCount int
	src      string
	hash     string
}

var scr Script

scr.hash = "some sha key"

scr.SendHash(some_args)

```

it seem to be a wrong way!

could anyone give some help?

sorry to my  pool english

**Comment by garyburd** [comment]
Use the connection [Do method](http://godoc.org/github.com/garyburd/redigo/redis#Conn.Do) to execute a script loaded through redis-cli:

     c.Do("EVALSHA", hash, numKeys, arg1, arg2)

A simpler approach is to use Redigo's [Script](http://godoc.org/github.com/garyburd/redigo/redis#Script) type.  The Script type optimistically executes  EVALSHA with a fallback to EVAL to handle the case where the script is not loaded.  Read the documentation and included example for information on how to use the type.
