### ISSUE TITLE
go1.5/FreeBSD: Pool.Get() extremely slow

### ISSUE THREAD

**Issue by nd2s** [garyburd/redigo#151]
Using Go 1.5 on FreeBSD (or with cross-compiling) `.Get()` on a newly created `Pool` blocks for ages.

My daemon creates two pools on startup and gets one connection each for sending a `.Ping()`. Startup time is around 2s with Go 1.4 and 2m30s with Go 1.5.

**Comment by garyburd** [comment]
The execution time for Get() on an empty pool is dominated by the application supplied dial function.  What does your dial function do?

**Comment by nd2s** [comment]
Thanks for the quick answer.

The dial function just uses `redis.Dial()`.

I have to apologise - it was not redigo's fault. Problem was that my Redis connection string used "localhost". Go 1.5 changed how DNS resolution works and on FreeBSD IPv6 is preferred. It seems it tried connecting to IPv6 where Redis was *not* listening and then after a (long) while switched back to IPv4.
