### ISSUE TITLE
Connection pool errors

### ISSUE THREAD

**Issue by adrianduke** [garyburd/redigo#152]
I'm experiencing some peculiar issues when putting redigo under load (~25 req/s). I'm utilising the pooll functionality to support the concurrent nature of my web service:

``` go
func newRedisPool(server, password string) *redis.Pool {
	return &redis.Pool{
		MaxIdle:     5,
		IdleTimeout: 240 * time.Second,
		Dial: func() (redis.Conn, error) {
			c, err := redis.Dial("tcp", server)
			if err != nil {
				return nil, err
			}
			if password != "" {
				if _, err := c.Do("AUTH", password); err != nil {
					c.Close()
					return nil, err
				}
			}
			return c, err
		},
		TestOnBorrow: func(c redis.Conn, t time.Time) error {
			_, err := c.Do("PING")
			return err
		},
	}
}
```
Pretty much straight from the Godoc with the additional password check. I'm grabbing a new connection per request with the following:

``` go
			conn := redisPool.Get()
			defer conn.Close()
			requests = NewRedisRequestStore(conn)
			tokenGenerator = NewRedisTokenGenerator(conn, "_token")
```

and I am using redis in a fairly primitive form with the RequestStore and TokenGenerator:

``` go
func NewRedisRequestStore(conn redis.Conn) *redisRequestStore {
	return &redisRequestStore{conn}
}

type redisRequestStore struct {
	redis.Conn
}

func (r redisRequestStore) Get(key string) (string, error) {
	return redis.String(r.Do("GET", key))
}

func (r redisRequestStore) Put(key, value string) {
	r.Do("SET", key, value)
}

func (r redisRequestStore) Delete(key string) error {
	_, err := r.Do("DEL", key)
	return err
}

func NewRedisTokenGenerator(conn redis.Conn, tokenKey string) *redisTokenGenerator {
	return &redisTokenGenerator{
		tokenKey: tokenKey,
		Conn:     conn,
	}
}

type redisTokenGenerator struct {
	tokenKey string
	redis.Conn
}

func (r redisTokenGenerator) Next() (int, error) {
	token, err := redis.Int(r.Do("INCR", r.tokenKey))
	if err != nil {
		return 0, err
	}
	return token
}
```

The errors I'm coming across are:

```
redigo: bad response line terminator (possible server error or unsupported concurrent read by application)
```

```
use of closed network connection
```

```
short write
```

These are all from the generator `Next()` method. Am I using it wrong? Its probably worth mentioning that I'm using rediscloud as well via heroku to host the redis instance (one of their larger plans, 1GB).

**Comment by garyburd** [comment]
The application is probably reading the connection concurrently. [Concurrent reads are not supported](http://godoc.org/github.com/garyburd/redigo/redis#hdr-Concurrency).

**Comment by garyburd** [comment]
My guess is that the application is accessing redisTokenGenerator concurrently.  Change it to:

   type redisTokenGenerator struct {
      tokenKey string
      p *redis.Pool
   }

func (r redisTokenGenerator) Next() (int, error) {
    c := r.p.Get()
    token, err := redis.Int(c.Do("INCR", r.tokenKey))
    c.Close()
    if err != nil {
        return 0, err
    }
    return token, nil
}

**Comment by adrianduke** [comment]
That looks like it has done it. Thanks for your help. I'm going to poke around my original code and try and find how it was reusing connection concurrently. It might be possible that the TokenGenerator and RequestStore were running at the same time or something.

Thanks!

**Comment by garyburd** [comment]
Does the application access a single TokenGenerator from multiple requests?
