### ISSUE TITLE
Pool mocking not possible, an interface might be required for redis.Pool  

### ISSUE THREAD

**Issue by satyasrikantmantha** [garyburd/redigo#154]
Hello,

I am implementing connection pooling in my api as described in the example. To test the commands I am using github.com/rafaeljusto/redigomock. However I dont see any option to mock the connection pool. I think if Pool type is refactored to be an interface, I would then be able to mock the method for Dial and return a mocked connection. 

In case there are any other alternatives please suggest.

Kind regards,
Satya.

**Comment by satyasrikantmantha** [comment]
One workaround what I found was to encapsulate the part to get the connection into a method and injected its mocked implementation in my test returning a mocked connection.

**Comment by garyburd** [comment]
You can define the interface in your application:

    type Pool interface {
         Get() redis.Conn
         // add more methods as needed by your application
    }

**Comment by garyburd** [comment]
Another option is to use *redis.Pool with [Dial](http://godoc.org/github.com/garyburd/redigo/redis#Pool.Dial) set to a function that returns a redigomock connection.
