### ISSUE TITLE
Support gopkg.in versioning 

### ISSUE THREAD

**Issue by MaerF0x0** [garyburd/redigo#159]
I'd like to use gopkg.in versioning with redigo. Sadly there aren't any tags  github.com/Clever/school-mdr-worker 

Could we start doing this?

**Comment by garyburd** [comment]
I will publish any changes that create a new version per the gopkg.in guidelines to a new package path. I'll consider using gopkg.in at that time.

Switching to gopkg.in before such a change creates work for existing users of the package with no benefit.

**Comment by garyburd** [comment]
@mhemmings  Please describe how you want the repo versioned and how you will take advantage of it.
