### ISSUE TITLE
How to maximize the performance of connection pool?

### ISSUE THREAD

**Issue by simon-xia** [garyburd/redigo#163]
What I tried is:

- `TestOnBorrow: nil`.
- `IdleTimeout:0`, to  avoid enter into loop when get a connection from pool

Any further suggestions? when performance comes first.

**Comment by garyburd** [comment]
I don't recommend setting IdleTimeout: 0 to improve performance.  The cost of checking for a timed out connection is small compared to the cost of a single call to the server.

I do not have further suggestions.
