### ISSUE TITLE
ZREM command doesn't work

### ISSUE THREAD

**Issue by prvn** [garyburd/redigo#166]
I am using redigo for my caching solution and realized that the ZREM command doesn't work and doesn't return any error either. You can try with very simple key like below
In redis cli:
```
127.0.0.1:8888> zadd test 1 "one"
127.0.0.1:8888> zadd test 2 "two"
127.0.0.1:8888> zadd test 3 "three"
127.0.0.1:8888> zadd test 4 "four"
127.0.0.1:8888> zadd test 5 "five"
```
In your code
```
ts := []string{"one", "two"}
c, _ := getRedisConnection()
r, e := c.Do("ZREM", "test", ts)
fmt.Println(r, e)
```
Back in redis cli:
```
127.0.0.1:8888> zrange test 0 -1
1) "one"
2) "two"
3) "three"
4) "four"
5) "five"
```

**Comment by elithrar** [comment]
What response are you getting when you print the response & error from
`c.Do("ZREM", "test", ts)` - you should get an integer response for the
number of elements removed (2, in your case).

**Comment by prvn** [comment]
I am not getting any error response, which caused this to go to production :)
I printed out response and error and it is
```
0 <nil>
```

**Comment by garyburd** [comment]
You are passing []string{"one", "two"} as a single argument to Redis.  Use one of the following:

    _, err := c.Do("ZREM", "test", "one", "two")

    _, err := c.Do("ZREM", redis.Args{}.Add("test").AddFlat(ts)...)

    args := []interface{}{"test"}
    for _, t := range ts {
        args = append(args, t)
    }
    _, err := c.Do("ZREM", args...)

**Comment by elithrar** [comment]
As a note: you may want to check that redis.Int(resp) == len(args) in a
situation like this.

Not deleting keys because they don't exist (due to invalid args) isn't an
error in Redis, but may generate one in your application.

**Comment by prvn** [comment]
I agree, should have checked the response count. Thanks for help.
