### ISSUE TITLE
pipeline bug? lost data

### ISSUE THREAD

**Issue by coolbeevip** [garyburd/redigo#167]
for i:=0;i<5000000;i++{
		err := conn.Send("LPUSH","users",strconv.Itoa(i))
		if(err!=nil){
			log.Println("error %s\n",err)
		}
		conn.Flush()
	}

	but in reds client command llen users  < 5000000

**Comment by elithrar** [comment]
You probably want to call `Flush()` outside of your loop otherwise you'll [attempt to] make 5,000,000 connections to Redis within a second or so.

**Comment by coolbeevip** [comment]
for i:=0;i<5000000;i++{
		err := conn.Send("LPUSH","users",strconv.Itoa(i))
		if(err!=nil){
			log.Println("error %s\n",err)
		}
	}
	conn.Flush()

        same error

**Comment by coolbeevip** [comment]
my code and run screen

func RedisGo() {
	redis.DialConnectTimeout(60*time.Second)
	conn, err := redis.Dial("tcp","127.0.0.1:6379")
	if err!=nil{
		log.Println("redis connect error %s",err)
	}else{
		log.Println("redis...")
		st := time.Now()
		PutSend(conn,5000000,"once")
		//goPut(conn);
		ed := time.Now()
		log.Printf("put use time %s\n",ed.Sub(st))	
		conn.Close()	
		log.Println("redis...ok")
	}
}

func PutSend(conn redis.Conn,count int,diff string){
	for i:=0;i<count;i++{
		err := conn.Send("LPUSH","users",diff+strconv.Itoa(i))
		if(err!=nil){
			log.Println("error %s\n",err)
		}
	}
	conn.Flush()
	rp,err := conn.Receive()
	if err!=nil{
		log.Println("error %s\n",err)
	}
	log.Println(rp)
}

<img width="869" alt="screen" src="https://cloud.githubusercontent.com/assets/4271525/12074633/420a0acc-b199-11e5-830d-da5645997076.png">

**Comment by FZambia** [comment]
It seems that your program exits before Redis receives all data, try this:

```
package main

import (
	"strconv"

	"github.com/garyburd/redigo/redis"
)

func main() {
	conn, err := redis.Dial("tcp", "127.0.0.1:6379")
	if err != nil {
		panic(err)
	}
	defer conn.Close()

	num := 5000000

	for i := 0; i < num; i++ {
		err := conn.Send("LPUSH", "users", strconv.Itoa(i))
		if err != nil {
			panic(err)
		}
	}
	conn.Flush()

	count := 0
	for count < num {
		_, err := conn.Receive()
		if err != nil {
			panic(err)
		}
		count++
	}
}
```

**Comment by coolbeevip** [comment]
@FZambia Great!!!
