### ISSUE TITLE
need help with ZUNIONSTORE and Args{}

### ISSUE THREAD

**Issue by zgiles** [garyburd/redigo#168]
Hello,
Just looking for some help with trying to make ZUNIONSTORE work. I thought maybe an issue would be quickest.

If I manually invoke the command with a set number of variables, it works fine.
But, if I try to build an Args list and send it, I always end up with a `"wrong number of arguments for 'zunionstore' command` error.
I've tried reading all the docs and library code, but I'm just missing something..

Works fine:
```
conn.Send("ZUNIONSTORE", tempkey, 1, "partialword:ma", "AGGREGATE", "SUM")
```
Doesn't work:
```
args := redis.Args{}
args.Add(tempkey)
args.Add("1")
args.Add("partialword:ma")
args.Add("AGGREGATE")
args.Add("SUM")
conn.Send("ZUNIONSTORE", args...)
```

Errors with:
`2016/02/01 13:04:02 ERR wrong number of arguments for 'zunionstore' command`

I've also tried removing the `AGGREGATE SUM` at the end, I tried removing the `1`, I tried making a `[]string{}` and passing it through AddFlat.. nothing seems to work.
Where am I off?

Thanks,
-Zach

**Comment by garyburd** [comment]
The Add method returns the result of appending the argument. The receiver is not modified (it's a value receiver).

Here's one way to write the code:

    args := redis.Args{}
    args = args.Add(tempkey)
    args = args.Add("1")
    args = args.Add("partialword:ma")
    args = args.Add("AGGREGATE") 
    args = args.Add("SUM")
    err := conn.Send("ZUNIONSTORE", args...)

See the [example](https://godoc.org/github.com/garyburd/redigo/redis#example-Args) for a more compact way to write the code.

**Comment by zgiles** [comment]
Ah shoot. What a silly mistake on my part... of course it makes sense now.
Thanks for setting me straight.
Works right away. 👍
