### ISSUE TITLE
ScanStruct + HGETALL from unexistent key

### ISSUE THREAD

**Issue by vpol** [garyburd/redigo#169]
```go
reply, err := redis.Values(conn.Do("HGETALL", key))
if err != nil {
    log.Fatal(err)
}

if err := redis.ScanStruct(reply, &somestruct); err != nil {
    log.Fatal(err)
}
```

Will not return any error, even if key doesn't exist, and there is "nothing" to scan.
Is there any way to get error from r.Values if HGETALL returns []?

**Comment by elithrar** [comment]
This behaviour matches Redis itself: http://redis.io/commands/hgetall

You could add a step to check len(reply) (which is of type []interface{})
before calling ScanStruct.

**Comment by garyburd** [comment]
The application should check for for len(reply) == 0 as suggested by @elithrar.
