### ISSUE TITLE
connection failure on redis URL whose path is just '/'

### ISSUE THREAD

**Issue by ancientHacker** [garyburd/redigo#173]
According to the [redis URL spec](https://www.iana.org/assignments/uri-schemes/prov/redis), a path part of '/' alone is valid, and refers to the default database (0) on the given host/port.  Thus, for example, the URI `http://localhost:9763/` should connect to the default database on the local redis instance.  But, when using redigo, this fragment:

```
func TestRedisConnect(t *testing.T) {
	_, err := redis.DialURL("redis://localhost:9763/")
	if err != nil {
		t.Errorf("Couldn't connect local with trailing slash: %v", err)
	}
}
```

fails with `invalid database: ` (where the database part is empty).

This has impact on clients that run on Heroku, because some Redis providers (such as Heroku Redis) provide URLs that do _not_ end in slash while others (such as RedisToGo) provide URLs that _do_ end in slash.  This issue forces client code to compensate for the difference in format.

I'm wondering if this is something you're willing to fix.  I'm happy to submit a pull request with a suggested fix, if so.

**Comment by garyburd** [comment]
Please send PR. Include a test case.

**Comment by ancientHacker** [comment]
PR submitted; CI build passes; test included; feedback welcome.
