### ISSUE TITLE
Returning errors properly with pipelines

### ISSUE THREAD

**Issue by bidesh** [garyburd/redigo#175]
Hi, 

With a command like the following:
```go
conn.Send("Multi")
conn.Send("HSET", "TEST_KEY", "field1", 10)
conn.Send("EXPIRE", "TEST_KEY", "a")   // error here. 
ret, err := conn.Do("EXEC")
log.Printf("Returned array: %+v          Error: %s\n", ret, err)
```
the values of `ret, err` is not being set properly. It outputs:
`Returned array: [0 ERR value is not an integer or out of range]          Error: %!s(<nil>)`

I see a problem in https://github.com/garyburd/redigo/blob/master/redis/conn.go#L433

http://redis.io/topics/protocol#resp-protocol-description shows that messages with first byte `-` is always errors. So, incase of errors it should be returned as error in from the `redigo/redis` package as well. The fix is really simple.

```go
	case '-':
		return nil, Error(string(line[1:]))
```

For pipelines commands, these error messages can be handled in many different ways before returning to the calling program. 

@garyburd Doesn't this make more sense? I would love to know your views on this. :) If you agree, I can create a PR!

Thanks!

**Comment by garyburd** [comment]
The returned value is `[]interface{}{int64(0), redis.Error("ERR value is not an integer or out of range")}`.  That's what I expect.  What do you expect instead?

**Comment by bidesh** [comment]
When I make the call, I would expect the success status code(updated, created...) to be returned in ret. In case of errors, I would like err parameter to be set instead. So that when I am calling it, I can check for err in case the operation didn't succeed and if there is a need for me to know details of the operation like did I create a new key, or if the key is not found anymore etc... I would dive into the array. 
What do you think about this?

**Comment by garyburd** [comment]
The EXEC command completes successfully. There is no error to set.

**Comment by bidesh** [comment]
Okay, I see your point. So, it seems iterating through the array seems to be the only option to know if any error occurred. The point would still be how to know if the value is actually an error. Checking if it is redis.Error seems to be the only option(?). 
Though it would be cool to have errors gathers for pipelined commands.

**Comment by garyburd** [comment]
The application must examine the array returned by EXEC to determine if an individual command in the transaction. Errors are represented as type redis.Error.

Gathering errors from the EXEC response seems like a useful feature.  This is different from gathering errors from a pipeline (Redigo does this already).

**Comment by bidesh** [comment]
Indeed! It is clarified now. Would this be considered a completely new feature which will be implemented only after a new maintainer is found?

**Comment by bidesh** [comment]
Closing this now since initial issue is clarified.
