### ISSUE TITLE
Only (P)SUBSCRIBE / (P)UNSUBSCRIBE / QUIT allowed in this context

### ISSUE THREAD

**Issue by the-world-wang** [garyburd/redigo#177]
I write it
```
redisConn.Do("PUBLISH","NEWS","122")
```
but it takes a error
does it mean that I can't publish something with this client

**Comment by garyburd** [comment]
An application cannot publish on a subscribed connection.

From the [Redis documentation](http://redis.io/topics/pubsub):

>  The commands that are allowed in the context of a subscribed client are SUBSCRIBE, PSUBSCRIBE, UNSUBSCRIBE, PUNSUBSCRIBE, PING and QUIT.
