### ISSUE TITLE
Pool Interface

### ISSUE THREAD

**Issue by clawconduce** [garyburd/redigo#179]
I have some code that passing around `redis.Conn` objects in order to unittest (using redigomock).  I'd like to use pass around `redis.Pool` objects since the function does not always connect to the db, and the `pool.Get()` call is not always needed.  In order to make unittesting possible, Pools need to be an interface so I can pass in mocked copies.  Is there any reason not to do so?

**Comment by garyburd** [comment]
See https://github.com/garyburd/redigo/issues/154#issuecomment-142298181

**Comment by clawconduce** [comment]
Thanks!  I missed that (forgot to search closed issues :/)
