### ISSUE TITLE
Also use TestOnBorrow to test new connections from Pool

### ISSUE THREAD

**Issue by baconalot** [garyburd/redigo#180]
It would be nice to also use the `TestOnBorrow` param to test newly created connections instead of only the idle ones. The fact that you can Dial an address does not mean that you have a working Redis connection, so it would be nice if that can be tested the same way.

pool.go

		// Dial new connection if under limit.

		if p.MaxActive == 0 || p.active < p.MaxActive {
			dial := p.Dial
			p.active += 1
			p.mu.Unlock()
			c, err := dial()
			if err != nil {
				p.mu.Lock()
				p.release()
				p.mu.Unlock()
				c = nil
	+		} else {
	+			test := p.TestOnBorrow
	+			if test != nil {
	+				err = test(c, time.Now())
	+				if err != nil {
	+					p.mu.Lock()
	+					p.release()
	+					p.mu.Unlock()
	+					c = nil
	+				}
	+			}
			}
			return c, err
		}

**Comment by garyburd** [comment]
The [Dial](https://godoc.org/github.com/garyburd/redigo/redis#Pool.Dial) function should test the connection.

**Comment by baconalot** [comment]
Ah, yes I see it returns a redis.Conn. Ok, will test the connection in there then.
