### ISSUE TITLE
Trouble releasing file handles

### ISSUE THREAD

**Issue by jmehic** [garyburd/redigo#183]
When running our binary our disk utilization starts going up and up without any obvious reason.  We're not doing any disk I/O in our app yet our utilization goes up.

We've written a simple test app that pings our Redis server every 10 seconds and monitored it with iotop and it seems that every few seconds the binary does a small bit of I/O.  By investigating temp files it looks as though the space is being taken up by Redis file handles.

Is it possible that when we access Redis with our app it causes a file handle to be created but never released, so the space remains taken even when the goroutine is done its work?  As soon as we kill the app all the disk space is freed, any ideas?

**Comment by garyburd** [comment]
The Redigo package does not create files.

Check to see that the application is [closing](https://godoc.org/github.com/garyburd/redigo/redis#Conn.Close) connections.  The application will leak file descriptors if the application does not close connections when the application is done with the connection.

**Comment by jmehic** [comment]
Thanks for the info, will take a look to make sure we're not missing any close operations.
