### ISSUE TITLE
Meet a problem when ScanStruct for self-define struct.

### ISSUE THREAD

**Issue by hikkikuma1991** [garyburd/redigo#184]
Forgive my poor English please.

I met a problem when I tried to use `func ScanStruct(src []interface{}, dest interface{}) error` to scan the data I got from redis.
I want to scan the data to my struct which is like this:
```
type Foo struct{
    Bar int 
    Baz sql.NullString
}
``` 
and when I run my program, It was printing a error
```
cannot convert from Redis bulk string to sql.NullString
```
is there any way to solve my problem?

**Comment by garyburd** [comment]
The supported field types are Integer, float, boolean, string and []byte types.  Can you use a string?

**Comment by hikkikuma1991** [comment]
Actually I can, but this may made my code ugly. Something like this
```
type dbFoo struct{
    Bar int 
    Baz sql.NullString
}

type redisFoo struct{
    Bar int 
    Baz string
}
```
But refer to encoding/jason.Marshal, it has an interface
```
// Marshaler is the interface implemented by objects that
// can marshal themselves into valid JSON.
type Marshaler interface {
	MarshalJSON() ([]byte, error)
}
``` 
so I can do like this,code:https://play.golang.org/p/hEVN_WuA86
```
package main

import (
	"database/sql"
	"encoding/json"
	"fmt"
)

type NullString struct {
	sql.NullString
}

func (r NullString) MarshalJSON() ([]byte, error) {
	return json.Marshal(r.String)
}

type Foo struct {
	Bar int        `json:bazr`
	Baz NullString `json:baz`
}

func main() {
	test := &Foo{
		Bar: 1,
		Baz: NullString{sql.NullString{
			String: "M",
			Valid:  true,
		}},
	}

	b, err := json.Marshal(test)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(string(b))
}
```

**Comment by garyburd** [comment]
Please describe higher-level problem that you are trying to solve.  If your goal is to store Foo values in Redis, then you can store a JSON or gob encoding of the Foo values.

**Comment by hikkikuma1991** [comment]
I think my problem should be "How to extend the ScanStruct function to support arbitrarily type?"

**Comment by garyburd** [comment]
Duplication of #46.
