### ISSUE TITLE
[feature idea] allow TestOnBorrow to run periodically

### ISSUE THREAD

**Issue by arodland** [garyburd/redigo#185]
Connection pools have `TestOnBorrow` which allows validating a connection when it's pulled out of the pool — pinging it to make sure it's still up, querying the role to make sure we still have the master, etc. — but on a busy connection that can be an awful lot of pinging. Right now we keep track of the time the connection was returned to the pool, for `IdleTimeout`, and also pass it to `TestOnBorrow`, but it would be interesting to keep track of the last time it was tested (or the time the connection was created, if it hasn't been tested yet), so that we could run the test once a second or something sensible like that.

One way to go about it would be adding another `time.Time` to `idleConn`, adding it to the signature of `TestOnBorrow`, and adding a bool to the return list of `TestOnBorrow` indicating whether the test was performed or skipped. That would be a breaking change for all users of pools, so maybe a new field? Or maybe this is a terrible idea? Figured I'd float it anyway.

**Comment by garyburd** [comment]
The time passed to TestOnBorrow is intended to be used for this purpose based on the assumption that the connection was good at the time the connection was returned to the pool.  

Can you give a scenario where the current TestOnBorrow API does not work?
