### ISSUE TITLE
PubSubConn.Close will block while used to subscribe redis sentinel channel 

### ISSUE THREAD

**Issue by RivenZoo** [garyburd/redigo#187]
I need sbuscribe sentinel channel `+switch-master` to get notified when master switched.  When PubSubConn.Close called to close connection, it will hang on until read timeout run out or block if read timeout set to 0.
It seems  stuck on line 347 [file redis/pool.go](https://github.com/garyburd/redigo/blob/master/redis/pool.go) when receive `ECHO` response from sentinel. 
While I use redis-cli to send `ECHO` to sentinel, it will receive response `(error) ERR unknown command 'echo'`. 
I don't know where goes wrong. Anybody can give me some hint?

System information following:
`go version`
> go version go1.6 darwin/amd64

`redis-sentinel -v`
> Redis server v=3.0.5 sha=00000000:0 malloc=libc bits=64 build=3145a5e1a81fd3f7

block goroutine information
>
1 @ 0x304f3 0x2aece 0x2a390 0x1a6cca 0x1a6d36 0x1a8b8a 0x1bcc64 0x1f3649 0x1f44ba 0x10991a 0x10a187 0x10b2a2 0x10dac5 0x10e5c8 0x10476c 0x23e3 0x5ea41
\#	0x2a390		net.runtime_pollWait+0x60						/Users/workspace/github/go/src/runtime/netpoll.go:160
\#	0x1a6cca	net.(*pollDesc).Wait+0x3a						/Users/workspace/github/go/src/net/fd_poll_runtime.go:73
\#	0x1a6d36	net.(*pollDesc).WaitRead+0x36						/Users/workspace/github/go/src/net/fd_poll_runtime.go:78
\#	0x1a8b8a	net.(*netFD).Read+0x23a							/Users/workspace/github/go/src/net/fd_unix.go:250
\#	0x1bcc64	net.(*conn).Read+0xe4							/Users/workspace/github/go/src/net/net.go:172
\#	0x1f3649	bufio.(*Reader).fill+0x1e9						/Users/workspace/github/go/src/bufio/bufio.go:97
\#	0x1f44ba	bufio.(*Reader).ReadSlice+0x21a						/Users/workspace/github/go/src/bufio/bufio.go:328
\#	0x10991a	github.com/garyburd/redigo/redis.(*conn).readLine+0x5a			/Users/workspace/go/src/github.com/garyburd/redigo/redis/conn.go:338
\#	0x10a187	github.com/garyburd/redigo/redis.(*conn).readReply+0x57			/Users/workspace/go/src/github.com/garyburd/redigo/redis/conn.go:411
\#	0x10b2a2	github.com/garyburd/redigo/redis.(*conn).Receive+0x162			/Users/workspace/go/src/github.com/garyburd/redigo/redis/conn.go:494
\#	0x10dac5	github.com/garyburd/redigo/redis.(*pooledConnection).Close+0x375	/Users/workspace/go/src/github.com/garyburd/redigo/redis/pool.go:348
\#	0x10e5c8	github.com/garyburd/redigo/redis.PubSubConn.Close+0x138			/Users/workspace/go/src/github.com/garyburd/redigo/redis/pubsub.go:71

**Comment by garyburd** [comment]
Unsubscribe the connection. Exit the receive loop and close the connection when the number of subscriptions is zero.

**Comment by RivenZoo** [comment]
Thanks a lot.
I add `Unsubscribe()` call before `Close()` then it won't block again.
But I still feel confused because `pooledConnection.Close` also sends 'UNSUBSCRIBE' command to redis.
The difference is `pooledConnection.Close` sent 'ECHO' after 'UNSUBSCRIBE' sent and it blocks on the following `Receive()` call. 
Again, thank you for your comment.^_^

**Comment by garyburd** [comment]
Were you calling Close and Receive concurrently?  That's not supported.

**Comment by RivenZoo** [comment]
Yes, I Receive in one goruntine and call Close in another goruntine.
My code looks like this

goruntine
\#1 for loop receive msg and do something

	for {
		reply := pubsub.Receive()
		switch reply.(type) {
		case redis.Message:
			// do something
		case redis.Subscription:
				if reply.Count == 0 {
					return
				}
		case error:
			return
	}

\#2 close connection to break for loop

	pubsub.Unsubscribe() // this is added
	pubsub.Close() // block

After line `pubsub.Unsubscribe() // this is added` added, in most case it won't block. But it blocks occasionally.
I intend to add some sync code to avoid Close and Receive concurrently called.

**Comment by garyburd** [comment]
It's blocking occasionally because there's a data race. You need to add code to avoid calling Close and Receive concurrently.

**Comment by RivenZoo** [comment]
It's really a elementary error. I should have considered it at first.
Thank you for your suggestion.
