### ISSUE TITLE
Scalability of Channels (Pub/Sub)

### ISSUE THREAD

**Issue by pjebs** [garyburd/redigo#188]
@garyburd I have a question I'm hoping you can help me with.

I'm building a real-time text based chat program where people can chat with ONLY 1 other person.
Each person can chat with 1 other person, but the aim is they can chat with Many people at once. (i.e. MANY one to one chats with different people). The aim is to have it scaleable, not necessarily to snapchat's level, but enough for 1 City.

I'm just wondering what is more scaleable:

* Having 1 channel for the **entire** application and filtering who the **message is for** and **who sent the message** based on the data encoded in the message

OR

* Having 1 channel for **each** person and all the different people sending messages to that person send their messages through that channel with data encoding **who sent the message**

OR

* Have an individual channel for EACH Chat between 2 people.

OR

* For Option 1 (1 channel for entire app), perhaps an intermediate solution of having 1 channel per city.

I'm wondering what approach is best for Go and Redis. If there is no clear cut answer, what the conditions/criteria are for making the decision.

**Comment by garyburd** [comment]
Redigo will not affect the scalability of these options. Pick what works best for your application.

**Comment by pjebs** [comment]
Should I use 1 connection to listen to multiple channels or 1 connection per channel or something in between?

Thanks @garyburd for response above.

**Comment by garyburd** [comment]
As a rule of thumb, an application should use a small and bounded number of connections per application instance.  The application should subscribe to multiple channels on a connection instead of creating a connection per channel.
