### ISSUE TITLE
Use of closed Network connections

### ISSUE THREAD

**Issue by vishal24tuniki** [garyburd/redigo#189]
@garyburd Even though i use the TestOnBorrow function, i keep getting the error
error: write tcp xxx.xx.xx.xxx:39103->xxx.xx.xx.xxx:6379: use of closed network connection
Can you please guide me on what might be the possible cases this might be happening ?

**Comment by garyburd** [comment]
The Redigo connection closes the underlying network connection on any error reading or writing to the underlying connection.  Print c.Err() to see if that gives a hint about the actual error.

**Comment by vishal24tuniki** [comment]
So basically you want me check exactly the below thing ?
conn := pool.Get()
_, err := conn.Do("HSET", "KEY", "key1", "val1")
if err !=nil {
    fmt..Println(conn.Err())
}

**Comment by garyburd** [comment]
Yes, that might indicate what the issue is.  What is your TestOnBorrow function?

**Comment by vishal24tuniki** [comment]
Exactly as the doc suggests
 TestOnBorrow: func(c redis.Conn, t time.Time) error {
            _, err := c.Do("PING")
            return err
        },

I also see there is a Close method on Conn interface, do you suggest calling conn.Close() in such cases to remove the connection from idle connection pool ? (Not really sure what to compare the err with, though)

**Comment by garyburd** [comment]
That's an example, not a suggestion.  Most applications don't need a TestOnBorrow function.

What does the Err() method report when you get the "Use of closed Network connection" error?

**Comment by vishal24tuniki** [comment]
Yes it's an example, though i don't see what else can be done in TestOnBorrow.
I will share the Err() return value when i run the test and such error happens

**Comment by vishal24tuniki** [comment]
Hi @garyburd, these are the errors conn.Err() returns for all "use of closed network connection"
read tcp xxx.xx.xx.xxx:54875->zzz.zz.zz.zzz:6379: read: connection reset by peer (very few)
read tcp xxx.xx.xx.xxx:60438->zzz.zz.zz.zzz:6379: i/o timeout (too many)

**Comment by garyburd** [comment]
Run your application with the [race detector](https://golang.org/doc/articles/race_detector.html) to see if that uncovers an issue.

Confirm that https://godoc.org/github.com/garyburd/redigo/redis#Pool.MaxIdle is set to a duration less than the server's timeout.

**Comment by vishal24tuniki** [comment]
Thanks @garyburd will try out the race detector.
Due to high concurrency of our application, we have set ActiveConnections and MaxIdle to 12k and IdleTimeout to 2mins. Do you see any issues with such settings ?

**Comment by garyburd** [comment]
The MaxActive and MaxIdle values seem very large to me.

Check to see if the app or the Redis server are hitting open file limits. 

Check for connection leaks. Log [the pool's active count](https://godoc.org/github.com/garyburd/redigo/redis#Pool.ActiveCount) at regular intervals to see if it's stable or increasing over time.

A two minute IdleTimeout may or may not be OK. Check that IdleTimeout is set to a duration less than the server's timeout.

**Comment by vishal24tuniki** [comment]
I always hit the maxActiveConns, such is the concurrency needed for the application. Will recheck the server's timeout. Thanks a lot @garyburd for the help :+1:

**Comment by garyburd** [comment]
Confirm that the server's `maxclient` limit is larger than `MaxActive`  The default `maxclient` is less than 12k.  

The application is opening a huge number of connections. Most applications can keep connection use low by avoiding long or blocking operations (other than calls to Redis) between the call to [Get()](https://godoc.org/github.com/garyburd/redigo/redis#Pool.Get) and the call to [Close()](https://godoc.org/github.com/garyburd/redigo/redis#Conn.Close).

**Comment by vishal24tuniki** [comment]
Yes @garyburd server's maxclient is kept at 60k, MaxActive 12k. All the

**Comment by vishal24tuniki** [comment]
Yes @garyburd server's maxclient is kept at 60k (64k open server & client ports), MaxActive 12k.

Regarding..
`The application is opening a huge number of connections. Most applications can keep connection use low by avoiding long or blocking operations (other than calls to Redis) between the call to Get() and the call to Close().`
Yes i refactored the code to take care this also. Even after all this, still have lots of i/o timeout. Trying to figure it out

**Comment by vishal24tuniki** [comment]
@garyburd Let's say for a pool
`wait:  true`
How much time does it wait a connection to be returned if pool is at maxActive limit?

**Comment by garyburd** [comment]
It waits until a connection is returned to the pool.  There is not a
timeout.

**Comment by vishal24tuniki** [comment]
ok
