### ISSUE TITLE
BLPOP SOME QUESTIONS

### ISSUE THREAD

**Issue by CarolMa** [garyburd/redigo#191]
1 When I use blpop, timeout parameter is set to 0, and sometimes I will not receive the first data, I'm sure I've made to the data in the redis, this situation does not occur every time, I have been very confused, I do not know if you come across the same problem?what is the mechanism of the long connection keep alive？

**Comment by garyburd** [comment]
The connection reads until the server returns a response, there's an error reading the connection or the [connection read timeout](https://godoc.org/github.com/garyburd/redigo/redis#DialReadTimeout) expires. Confirm that the connection read timeout is less than the BLPOP timeout. 

I sugguest turnning the [MONITOR](http://redis.io/commands/MONITOR) command to determine where the first item is going. Perhaps another instance of the app that's popping the item.

**Comment by CarolMa** [comment]
Thank you, I try
