### ISSUE TITLE
add a Int64s() function

### ISSUE THREAD

**Issue by chenjie4255** [garyburd/redigo#192]
AFAIK there is no function Int64s for redis reply, I thinks it is necessary for a int64 array.

**Comment by ankitm123** [comment]
I will take a look at this issue, and come out with a fix.

**Comment by GlenDC** [comment]
How is it going with your implementation, @ankitm123?

**Comment by ankitm123** [comment]
I will be done by this weekend @GlenDC

**Comment by crackerplace** [comment]
submitted a pr for this as I did not see any activity here.please let me know if you have any issue.thanks.

**Comment by garyburd** [comment]
200b674d7407b7ff1b36b46f1cd853180d5e5298
