### ISSUE TITLE
conn.Close() problem

### ISSUE THREAD

**Issue by guojun1992** [garyburd/redigo#193]
hello 

conn := Pool.Get()
defer conn.Close()

conn close method why not put the conn into pool?

func (c *conn) Close() error {
	c.mu.Lock()
	err := c.err
	if c.err == nil {
		c.err = errors.New("redigo: closed")
		err = c.conn.Close()
	}
	c.mu.Unlock()
	return err
}

**Comment by garyburd** [comment]
Close does return the the pool to the connection.  [Here's the code.](https://github.com/garyburd/redigo/blob/b8dc90050f24c1a73a52f107f3f575be67b21b7c/redis/pool.go#L324-L360)

**Comment by guojun1992** [comment]
but the pool's Get method return Conn not pooledConnection

so i used Conn.Close method not pooledConnection'Close method

**Comment by guojun1992** [comment]
my fault the Get method return &pooledConnection{p: p, c: c} ,i see

thanks for your help.
