### ISSUE TITLE
about command hgetall

### ISSUE THREAD

**Issue by luodw** [garyburd/redigo#194]
When we get a  key use commond  'hgetall' , if the key is not exist in redis , 
strMap, err := redis.StringMap(redisClient.Do("hgetall", "test))   will return a empty map;
so i want to know why it do not return a nil like command get ? it will be more fit for our cognition;

**Comment by garyburd** [comment]
Write a helper function to return nil on missing key:

    func stringMapOrNil(v interface{}, err error) (map[string]string, error) {
        if values, ok := v.([]interface{}); ok && len(values) == 0 {
          return nil, nil
        }
        return redis.StringMap(v, err)
    }

**Comment by luodw** [comment]
ok, thank you.
