### ISSUE TITLE
Preferred way of closing a connection

### ISSUE THREAD

**Issue by donileo** [garyburd/redigo#199]
What would be the preferred way of closing a connection in redigo

Method 1:
```
func RedisDoSomething(rp *RedisPool) error {
rc:=rp.Get()
defer rc.Close()
_,err := rc.Do("do something....")
if err != nil {
return err
}

//do some potentially longer stuff here
return nil
}
```

OR

Method 2:
```
func RedisDoSomething(rp *RedisPool) error {
rc:=rp.Get()
_,err := rc.Do("do something....")
rc.Close()
if err != nil {
return err
}

//do some potentially longer stuff here
return nil
}
```

Method #1 will  close the connection _after_ the function returns which may take some time and will therefore hold the connection open longer then necessary.

Method #2 will close the connection as soon as possible but will add some delay for the function to return due to the Close method being synchronous and taking locks.

Im liking method #2 but it would really be nice if there was a CloseAsync() method which would close the Connection in a go routine -- assuming that would be safe.

Thoughts on which is preferred?

**Comment by elithrar** [comment]
Have you measured how long it blocks for?

**Comment by donileo** [comment]
You mean the rc.Close()? No. I was hoping maybe you would know on the average case :), I haven't done any tests. It would be nice to know though for sure, but I'm assuming closing the connection right after you are done using it should still be faster in most cases then waiting for a potentially long function to exit. Method #2 also has the tradeoff that the rc variable still lives and a rc.Do("....") may be called after your close, but that would be a programmer error and definitely needs to be looked for.

**Comment by garyburd** [comment]
Method 1 may require more open connections to the server than method 2. If the number of open connections is not a concern, then use the method that works best for your application code.

The average time that an application blocks on a pool lock is small compared to the time required to execute a single Redis command. Let me know if you have tests that show the pool lock is a performance issue.

An application can close a connection asynchronously with:
  
    go rc.Close()

**Comment by donileo** [comment]
@garyburd cool thanks.

**Comment by zhangruiskyline** [comment]
Hi @garyburd do we need to close connection regardless of redis is successfully or not in process? here close connection basically give back connection to connection pool for later use?

**Comment by garyburd** [comment]
@zhangruiskyline Connections must be closed in all cases.
