### ISSUE TITLE
Should I call conn := pool.Get() everytime ?

### ISSUE THREAD

**Issue by commit-master** [garyburd/redigo#201]
Hi, 

I really cannot find any informations on this on the web.. So as a desperate attempt, I'm asking here. Right now, I have made an API using mux router, and I'm using `pool = newPool(*redisServer)` in my main() function.

But then in each of my routes, I use `conn := pool.Get()` so I can store/retrieve things from my Redis instance. Is it the right way of doing things ?

Also, should I use defer `conn.Close(),` each time I use `conn := pool.Get()` ?

Thanks.

**PS: Sorry for using the issue system to get my answer, I know it's not meant for that**

**Comment by garyburd** [comment]
The [pool documentation](https://godoc.org/github.com/garyburd/redigo/redis#Pool) describes how to use a pool in HTTP request handlers.  Requests handlers should [Get](https://godoc.org/github.com/garyburd/redigo/redis#Pool.Get) a connection from the pool and [Close](https://godoc.org/github.com/garyburd/redigo/redis#Conn.Close) the connection when done:

    func serveHome(w http.ResponseWriter, r *http.Request) {
      conn := pool.Get()
      defer conn.Close()
      ....
    }

**Comment by commit-master** [comment]
Ah thank your for the quick and clear reply 👍 !
