### ISSUE TITLE
[CLIENT LIST] command 

### ISSUE THREAD

**Issue by IceiceFire** [garyburd/redigo#203]
keys, err := redis._**Strings**_(conn.Do("CLIENT LIST"))

How to receive return results?

**Comment by garyburd** [comment]
The client list command returns a bulk string. The format of the string is described [in the Redis documentation](http://redis.io/commands/client-list).  You can get the bulk string as a Go string using:

	r, err := redis.String(c.Do("CLIENT", "LIST"))

or as a []byte using:

 	r, err := redis.Bytes(c.Do("CLIENT", "LIST"))

**Comment by IceiceFire** [comment]
thank you
