### ISSUE TITLE
Convert map[string]string from redigo to json

### ISSUE THREAD

**Issue by commit-master** [garyburd/redigo#204]
Hi,

I'm using the following command to query some data from redigo :

```
val, err := redis.StringMap(conn.Do("HGETALL", "CHAT::"+userIds[0]+":"+userIds[1]))
if err != nil {
  panic(err)
}
```

which works great and returns me :

```
map[1473872583:{"user":"USER_01","reciever":"USER_00","message":"THIS_IS_A_MESSAGE"} 1473872584:{"user":"USER_01","reciever":"USER_00","message":"THIS_IS_ANOTHER_MESSAGE"}]
```

Now I need to convert that has a `json`, I've been trying a lot of different things, especially `Marshalling` it, but all it returns me does not work. Am I missing something there ?

**EDIT :** When `Marshalling` I get the following value :
```
[123 34 49 52 55 51 56 55 52 51 49 48 34 58 34 123 92 34 117 115 101 114 92 34 58 92 34 48 92 ... 125]
```
Thanks !

**Comment by garyburd** [comment]
You are marshalling the value correctly, but printing it as bytes.  Try this:

    fmt.Printf("%s", p)

where `p` is the result from json.Marshal.
