### ISSUE TITLE
Can redigo get the cost time of rediscmd?

### ISSUE THREAD

**Issue by jinleileiking** [garyburd/redigo#205]

**Comment by garyburd** [comment]
- The Redis command documentation gives the time complexity for each command.  
- The [slowlog](http://redis.io/commands/slowlog) can be used to log slow commands. 
- An application write a wrapper around connections to record times.  See [logging connection](https://github.com/garyburd/redigo/blob/ffa8d46ada782d81cfda81a0fbd9f45ceae448e8/redis/log.go#L24) code for an xampel of how to write such a wrapper.

**Comment by jinleileiking** [comment]
Thanks. It seem use xampel code can do this job. If redigo have this feature, it is the best.
