### ISSUE TITLE
Trouble getting high performance with pipelining

### ISSUE THREAD

**Issue by kellabyte** [garyburd/redigo#206]
I'm not sure if I've implemented this correctly but I'm trying to match a pipelining HTTP service with pipelined Redis requests. I can get 200,000 HTTP requests/second but only 20,000 requests/second with Redis requests included. Using `redis-benchmark` I can get over a million operations/second.

# Source
```
package main

import (
	"fmt"
	"log"
	"os"
	"strconv"
	"time"

	"github.com/garyburd/redigo/redis"
	"github.com/valyala/fasthttp"
)

var pool *redis.Pool
var pipelinedRequests int

func main() {
	if len(os.Args) < 3 {
		log.Panic("Must provide Redis server address, number of connections and number of pipelined requests.")
	}
	server := os.Args[1]
	connections, err := strconv.ParseInt(os.Args[2], 10, 64)
	if err != nil {
		log.Panic("Must provide Redis server address, number of connections and number of pipelined requests.")
	}
	pipelined, err := strconv.ParseInt(os.Args[3], 10, 64)
	if err != nil {
		log.Panic("Must provide Redis server address, number of connections and number of pipelined requests.")
	}

	pipelinedRequests = int(pipelined)
	pool = newRedisPool(server, int(connections))
	go startNullHTTPServer()
	startRedisHTTPServer()
}

func newRedisPool(server string, connections int) *redis.Pool {
	return &redis.Pool{
		MaxIdle:     connections,
		MaxActive:   connections,
		IdleTimeout: 240 * time.Second,
		Dial: func() (redis.Conn, error) {
			c, err := redis.Dial("tcp", server)
			if err != nil {
				return nil, err
			}
			return c, err
		},
		TestOnBorrow: func(c redis.Conn, t time.Time) error {
			if time.Since(t) < time.Minute {
				return nil
			}
			_, err := c.Do("PING")
			return err
		},
	}
}

func startNullHTTPServer() {
	log.Print("Null HTTP listening on :8080")
	if err := fasthttp.ListenAndServe(":8080", nullRequestHandler); err != nil {
		log.Fatalf("Error in ListenAndServe: %s", err)
	}
}

func startRedisHTTPServer() {
	log.Print("Redis HTTP listening on :8081")
	if err := fasthttp.ListenAndServe(":8081", redisRequestHandler); err != nil {
		log.Fatalf("Error in ListenAndServe: %s", err)
	}
}

func nullRequestHandler(ctx *fasthttp.RequestCtx) {
	ctx.Response.SetStatusCode(200)
}

func redisRequestHandler(ctx *fasthttp.RequestCtx) {
	conn := pool.Get()

	key := ctx.Request.Header.Peek("key")
	value := ctx.Request.Header.Peek("value")

	err := conn.Send("SET", key, value)
	if err != nil {
		ctx.Response.SetStatusCode(500)
		fmt.Println(err)
	} else {
		ctx.Response.SetStatusCode(200)
	}
	if ctx.ConnRequestNum()%uint64(pipelinedRequests) == 0 {
		conn.Do("")
	}
	conn.Close()
}
```

# Prerequisites 
```
git clone https://github.com/antirez/redis.git
cd redis;make;cd..
redis/src/redis-server &

git clone https://github.com/wg/wrk.git
cd wrk;make;cd..
cp wrk/wrk .
```

# Running the HTTP to Redis server
```
go run redis_benchmark.go localhost:6379 32 32
```

# Example results
No Redis operations just HTTP requests.
```
./wrk --latency --script set_random.lua -t 4 -c 32 -d 10s http://127.0.0.1:8080 -- 32
Running 10s test @ http://127.0.0.1:8080
  4 threads and 32 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.06ms  592.15us   9.68ms   61.29%
    Req/Sec    69.34k     9.79k  108.48k    74.00%
  Latency Distribution
     50%    1.38ms
     75%    2.06ms
     90%    0.00us
     99%    0.00us
  2769504 requests in 10.04s, 245.63MB read
Requests/sec: 275735.73
Transfer/sec:     24.46MB
```

HTTP requests with Redis requests.
```
./wrk --latency --script set_random.lua -t 4 -c 32 -d 10s http://127.0.0.1:8081 -- 32
Running 10s test @ http://127.0.0.1:8081
  4 threads and 32 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    13.50ms   11.70ms  48.44ms   15.73%
    Req/Sec     7.24k     1.27k   10.34k    63.50%
  Latency Distribution
     50%    0.00us
     75%    0.00us
     90%    0.00us
     99%    0.00us
  288960 requests in 10.03s, 25.63MB read
Requests/sec:  28809.26
Transfer/sec:      2.56MB
```

**Comment by garyburd** [comment]
Because a pooled connection returns the underlying connection to a neutral state in `Close()`, the handler in the issue will have the same performance as:

    func redisRequestHandler(ctx *fasthttp.RequestCtx) {
        conn := pool.Get()
        defer conn.Close()
        key := ctx.Request.Header.Peek("key")
        value := ctx.Request.Header.Peek("value")
        _, err := conn.Do("SET", key, value)
        if err != nil {
            ctx.Response.SetStatusCode(500)
            fmt.Println(err)
        } else {
            ctx.Response.SetStatusCode(200)
        }
    }

What are your requirements for handling SET command errors?  Do you want to log the errors, return 500 from the handler or something else? I'll make suggestions based on your answer.

**Comment by kellabyte** [comment]
Since I'm trying to map 1:1 HTTP<-->Redis requests I think the correct thing to do is return a HTTP 500.

**Comment by garyburd** [comment]
To return 500 status on Redis command error, the application's request handler must send the command (including flushing the command to network) and receive the response.  If the application uses a pool, then the application should implement the send/flush/receive by calling `Do()` as shown in my previous response.

The [ConnMux](https://godoc.org/github.com/garyburd/redigo/redisx#ConnMux) is an alternative to using a pool.  It's possible that ConnMmux will have  better performance than a pool in this scenario.

Does fasthttp provide a way for the application to execute requests in an HTTP pipeline concurrently?  If so, there might be a way to extend the pipelining at the HTTP level through the application to the Redis server.

If fasthttp does not allow the application to access the pipeline, then consider pipelining at the application level by sending multiple key-value pairs in a request.  

    conn := pool.Get()
    defer conn.Close()
    // this code uses net/http API. I don't know how do this with fasthttp.
    r.ParseForm()
    for k, vs := range r.Form {
        if len(vs) > 0 {
            conn.Send("SET", k, vs[0])
        }
    }
    _, err := conn.Do("")
    return err

**Comment by kellabyte** [comment]
I don't think you need the ability to execute requests concurrently. HTTP pipelining can do just fine processing over a million HTTP requests/second in a single thread. HTTP pipelining is a network optimization where you can send multiple requests over the network in sequence without waiting for any of the replies which allows better utilization of the network. You don't need concurrent request handling to do this.

The same should be possible with Redis pipelining. Sometimes batching is conflated with pipelining. Pipelining is full duplex IMO.

**Comment by garyburd** [comment]
If the application can only execute one request at a time from the HTTP pipeline, then requests in the pipeline block on the completion of earlier requests in the pipeline.  In the example application, each request blocks on a round trip to the Redis server. This limits the throughput over a single connection.

Redigo's pipelining is full duplex.  Redigo does not implement batching.

**Comment by garyburd** [comment]
Are you using an HTTP client that supports pipelining outside of your benchmarks?  Many HTTP clients, including the net/http client, do not pipeline requests over http/1.1.

**Comment by garyburd** [comment]
The application requirements as I understand them prevent pipelining commands to Redis.  

Perhaps you can make progress by starting with an application that does pipeline commands.  For example:

    func send(conn redis.Conn, n int) {
            for i := 0; i < n; i++ {
                    if err := conn.Send("SET", "key", "value"); err != nil {
                            log.Fatal(err)
                    }
            }
            if err := conn.Flush(); err != nil {
                    log.Fatal(err)
            }
    }

    func receive(conn redis.Conn, n int) {
            for i := 0; i < n; i++ {
                    _, err := conn.Receive()
                    if err != nil {
                            log.Fatal(err)
                    }
            }
    }

    func main() {
            conn, err := redis.Dial("tcp", ":6379")
            if err != nil {
                    log.Fatal(err)
            }
            go send(conn, *totalRequests)
            receive(conn, *totalRequests)
    }       

I am closing this issue because it's an application design issue, not an issue with Redigo.

**Comment by kellabyte** [comment]
I have a question about `Send()` and `Flush()`. Does `Send()` batch requests until `Flush()` or does it start sending down the TCP socket immediately?

**Comment by garyburd** [comment]
Connections write to the underlying network connection using a [`bufio.Writer`](https://github.com/garyburd/redigo/blob/ffa8d46ada782d81cfda81a0fbd9f45ceae448e8/redis/conn.go#L46).  Data is written to the network when the `Writer`'s buffer fills and when [`Flush()`](https://github.com/garyburd/redigo/blob/ffa8d46ada782d81cfda81a0fbd9f45ceae448e8/redis/conn.go#L487) is called.
