### ISSUE TITLE
Type Convert Err

### ISSUE THREAD

**Issue by pandanrain** [garyburd/redigo#209]
In my  Redis I set  currencyRate => "6.77854"
so use ` redis.Do("HGET", key, 'currencyRate') `  return a []uint8  value [54 46 56 53 53 50 48 52]
so i  turn []uint8 to  float use : `values, err := redis.Float64(baseRate, nil)`
but the result turn out to be `6.855204` which is not equal to the original value
what can i do  to get the origin value

**Comment by garyburd** [comment]
The value `[]byte{54, 46, 56, 53, 53, 50, 48, 52}` returned from Redis is the string `"6.855204"`.   That matches resulting floating point value.  There is no conversion error.

Redigo and Redis are return the byte values saved by the application.  Check your application for possible errors.

**Comment by pandanrain** [comment]
thanks for you replay.
I checked my application again, there is something wrong with my application.
Redigo works well ,and i will close this issue!
