### ISSUE TITLE
Documentation should mention that connections are closed on errors

### ISSUE THREAD

**Issue by Gaffney** [garyburd/redigo#211]
[`fatal(err)` closes the connection](https://github.com/garyburd/redigo/blob/master/redis/conn.go#L291-L295), and `fatal(err)` is called in [every failure case of `Do(...)`
](https://github.com/garyburd/redigo/blob/master/redis/conn.go#L581-L612)

This should be documented, or people may erroneously think they can reuse (e.g. retry with) the connections that issued failed requests.

**Comment by garyburd** [comment]
`Do()` returns command errors without calling `fatal`.

Applications should call  the connection `[Err()](https://godoc.org/github.com/garyburd/redigo/redis#Conn.Err)` method to determine if the connection is reusable.

**Comment by Gaffney** [comment]
@garyburd I am confused by your response as fatal is called in `Do()` 4 times:
- [conn.go#L582](https://github.com/garyburd/redigo/blob/master/redis/conn.go#L582)
- [conn.go#L587](https://github.com/garyburd/redigo/blob/master/redis/conn.go#L587)
- [conn.go#L599](https://github.com/garyburd/redigo/blob/master/redis/conn.go#L599)
- [conn.go#L611](https://github.com/garyburd/redigo/blob/master/redis/conn.go#L611)

> Applications should call the connection Err() method to determine if the connection is reusable.

That is precisely what would be a great addition to the documentation to avoid any incorrect assumptions :)

**Comment by Gaffney** [comment]
This is kind of implied in `Err()`: `... Applications should close broken connections.`; just would be nice if the above was a little more explicit IMO.

**Comment by garyburd** [comment]
There are two classes of errors returned from the connection.

- Command errors returned from the server.  The `fatal` function is **not** called for these errors.  The application can continue using the connection after one of these errors is returned.
- Protocol and connection errors.  The `fatal` function is called because there's no recovery from one of these errors.

I will improve the documentation.

**Comment by garyburd** [comment]
See https://godoc.org/github.com/garyburd/redigo/redis#hdr-Errors.
