### ISSUE TITLE
is it legal??

### ISSUE THREAD

**Issue by minki4013** [garyburd/redigo#212]
type Pool, in document, commented like this
"The connection returned from Dial must not be in a special state (subscribed to pubsub channel, transaction started, ...)."

so, can i use transaction like this?? (use connection pool...)

func newPool(server, password string) *redis.Pool {
    return &redis.Pool{
        MaxIdle: 3,
        IdleTimeout: 240 * time.Second,
        Dial: func () (redis.Conn, error) {
            c, err := redis.Dial("tcp", server)
            if err != nil {
                return nil, err
            }
            if _, err := c.Do("AUTH", password); err != nil {
                c.Close()
                return nil, err
            }
            return c, err
        },
        TestOnBorrow: func(c redis.Conn, t time.Time) error {
            if time.Since(t) < time.Minute {
                return nil
            }
            _, err := c.Do("PING")
            return err
        },
    }
}

var (
    pool *redis.Pool
    redisServer = flag.String("redisServer", ":6379", "")
    redisPassword = flag.String("redisPassword", "", "")
)

func main() {
    flag.Parse()
    pool = newPool(*redisServer, *redisPassword)
    ...
}

func serveHome(w http.ResponseWriter, r *http.Request) {
    **c := pool.Get()
    defer conn.Close()
    c.Send("MULTI")
    c.Send("INCR", "foo")
    c.Send("INCR", "bar")
    ret, _ := c.Do("EXEC")**
    fmt.Fprint(w, ret) // prints [1, 1]
}

**Comment by garyburd** [comment]
Yes, this is legal. The dial function does not start a transaction, subscribe to a pubsub channel or execute any other command that puts the connection in a special state.
