### ISSUE TITLE
Redigo support GEOPOS command?

### ISSUE THREAD

**Issue by xkeyideal** [garyburd/redigo#214]

**Comment by xkeyideal** [comment]
Can  the newest master branch support it?

**Comment by garyburd** [comment]
GEOPOS is supported in every version of Redigo including the current master. 

Most users of the GEOPOS command will want to convert the return value to [][2]float64.  You can write this conversion in your application. I will accept a pull request to add a helper function that will do the conversion.

**Comment by xkeyideal** [comment]
Understand

**Comment by garyburd** [comment]
Superseded by more general issue #230.
