### ISSUE TITLE
Used redigo pool, Got many read: connection reset by peer

### ISSUE THREAD

**Issue by Icedroid** [garyburd/redigo#215]
Who can help me for these error:

![qq 20161210115711](https://cloud.githubusercontent.com/assets/674647/21071076/5fc6ae04-bed0-11e6-97cc-6bfdc35776a8.png)

```
$netstat -antup | grep :6379 | grep "establish" | wc -l
89132
```

my pool init with mactActive=4000 maxIdle=300 idleTimeout=500s ,redis server timeout is 600s

![qq 20161210115647](https://cloud.githubusercontent.com/assets/674647/21071086/b0ce5cc0-bed0-11e6-89e6-d9303ebd5012.png)

**Comment by garyburd** [comment]
My guess is that your application is leaking connections.  How many connections are [active](https://godoc.org/github.com/garyburd/redigo/redis#Pool.ActiveCount)?  What are the fd limits on your application and the server?

**Comment by zhangruiskyline** [comment]
I also had this issue, any recommendation for active/idle and timeout setup?

**Comment by zhangruiskyline** [comment]
@garyburd what kind of leaking connection scenario could be? I am using redigo to connect to a Azure redis cache service

**Comment by garyburd** [comment]
> what kind of leaking connection scenario could be?

Not closing the connections.

> active/idle and timeout

Set MaxActive to a value greater than the number of connections you expect the application to use.

Increase MaxIdle when you find the pool is dialing new connections more frequently than you would like.

**Comment by zhangruiskyline** [comment]
Thanks, so to deal with leaking connection, we need to make sure that if redis access has any error(like time out), we will need to close that connection?

**Comment by zhangruiskyline** [comment]
Is below code looks buggy? I always got some "internal/poll.TimeoutErr" when I use connection poll

func GetRedisClient(cachekey string, redisClientURL string) (*RedisCache, error) {
	
	redispool := redis.Pool{
		MaxActive: 50,
		MaxIdle: 25,  // adjust to your needs
		IdleTimeout: 200 * time.Second,  // adjust to your needs
		Dial: func () (redis.Conn, error) {
			redisConnStart := time.Now()
			c, err := redis.Dial("tcp", redisClientURL, redis.DialReadTimeout(redisReadTimeout))
			redisConnDuration := time.Since(redisConnStart)
			log.Infof("redis connection latency = s%",redisConnDuration)
			if err != nil {
				log.Errorf(err.Error())
				errInfo = err
				return nil, err
			}
			if _, err := c.Do("AUTH", cachekey); err != nil {
				log.Errorf(err.Error())
				c.Close()
				return nil, err
			}
			log.Infof("redis connection success")
			return c, err

		},
	}
	client.CacheConn = &redispool

	return &client, client.CacheConn.Get().Err()

}

func (c *RedisCache) ReadRedisCache(key string, opIds util.LogOperationIds)  (string) {
	//cache performance check
	client := c.CacheConn.Get()
	logFields := opIds.LogFields()
	redisAccessStart := time.Now()
	value, err := redis.String(client.Do("GET", key))
	redisAccessDuration := time.Since(redisAccessStart)
	util.TrackPerformanceMetric("RedisLatency", float32(redisAccessDuration), opIds)
	if err != nil{
		if  err != redis.ErrNil {
			log.WithFields(logFields...).Errorf("redis error = %s", err)
			client.Close()
		} else {
			util.TrackCustomEvent("Cache Miss")
		}
	} else {
		util.TrackCustomEvent("Cache Hit")
	}
	//todo: add customer error to wrap redis return error and propagate
	return value
}

**Comment by zhangruiskyline** [comment]
When I only use one connection instead of connection pool. unit test can pass, here is what code looks like

but I always get error like 
redis error = read tcp 10.244.0.157:59136->104.45.237.250:6380: use of closed network connection
redis error = redigo: unexpected response line (possible server error or unsupported concurrent read by application)

and then lots of 

redis error = tls: use of closed connection

`		
redisConnStart := time.Now()
		c, err := redis.Dial("tcp", redisClientURL,
			redis.DialUseTLS(true))
		redisConnDuration := time.Since(redisConnStart)
		log.Infof("redis connection latency",redisConnDuration.Nanoseconds())
		if err != nil {
			log.Errorf("redis connection error",err)
			errInfo = err
		} else {
			redisAuthtart := time.Now()
			response, err := c.Do("AUTH", cachekey)
			redisAuthDuration := time.Since(redisAuthtart)
			log.Infof("redis connection latency",redisAuthDuration.Nanoseconds())
			if err != nil {
				log.Errorf("redis auth error",err)
				errInfo = err
			} else {
				log.Infof("redis connection created with % \n", response)
				client.CacheConn = c
			}
		}
`

**Comment by garyburd** [comment]
The application must close the connection in ReadRedisCache.

The usual cause of "redigo: unexpected response line" is a data race in the application.  Run your application with the race detector.

**Comment by zhangruiskyline** [comment]
@garyburd thanks, in this case, do you recommend to use redis connection pool instead of open and close connections when data comes?

**Comment by zhangruiskyline** [comment]
@garyburd another question, for the redis.DialConnectTimeout(). is it the first time connection timeout? or it is time to fetch a idle connection from a existing connection pool?

**Comment by garyburd** [comment]
@zhangruiskyline I don't know enough about your application to determine if opening and closing connections is better than using pool.

The function redis.DialConnectTimeout timeout for connecting to the Redis server.  The option is unrelated to the pool.
