### ISSUE TITLE
Example newPool function throw error when supplied with empty password during AUTH

### ISSUE THREAD

**Issue by GamingCoder** [garyburd/redigo#216]
I used the example newPool function to create a new connection pool. When I used it I got the error `ERR Client sent AUTH, but no password is set`. This happens as a result of the execution of the `AUTH` command with the empty password as parameter.

I did fix the error in my version. The function should be
```go
func newPool(server, password string) *redis.Pool {
  return &redis.Pool{
    MaxIdle:     3,
    IdleTimeout: 240 * time.Second,
    Dial: func() (redis.Conn, error) {
      c, err := redis.Dial("tcp", server)
      if err != nil {
        return nil, err
      }
      if password != "" {
        if _, err = c.Do("AUTH", password); err != nil {
          c.Close()
          return nil, err
        }
      }
      return c, err
    },
    TestOnBorrow: func(c redis.Conn, t time.Time) error {
      if time.Since(t) < time.Minute {
        return nil
      }
      _, err := c.Do("PING")
      return err
    },
  }
}
```

**Comment by garyburd** [comment]
If your application does not require authentication, then don't copy this example.

**Comment by GamingCoder** [comment]
While I agree with you that providing a dial only function would be the right way to do it when no password is needed, I think that the example function should handle both cases to provide a seamless setup of the client for beginners.

**Comment by garyburd** [comment]
The purpose of the example is to demonstrate how to use features of the pool. The example is not a recommended configuration.

**Comment by garyburd** [comment]
I will reduce the example to the minimum required to use the pool and mention the other features separately.

**Comment by garyburd** [comment]
Fixed by https://github.com/garyburd/redigo/commit/0708def8b0cf3a05acdf44a7f28b864c2958921d.
