### ISSUE TITLE
Errors using UnixNano() as score for sorted set

### ISSUE THREAD

**Issue by numair** [garyburd/redigo#218]
I'm probably just dumb, but here's a problem I've found.  I tried to store the scores for a sorted set as UnixNano() values; when I try to get them out of Redis using redigo, I get the following error:

redigo.Scan: cannot assign to dest 1: strconv.ParseInt: parsing "1.4812916317996959e+18": invalid syntax

When I look at how Redis has stored the value in the database, this is what I see:

ZRANGE sorted_set_10 0 -1 WITHSCORES
1) "53"
2) "1.4812916317996959e+18"

... So it seems that Redis is storing the number (string?) correctly, but it isn't getting read out properly back into Go.  I've since converted my work to use normal Unix() second-based times, and everything is fine, but perhaps this will pop up again, and maybe it's worth resolving?  Looking forward to your thoughts.

**Comment by garyburd** [comment]
Redis sorted set scores are floating point values. The application should scan floating point values to a float64 or float32.

**Comment by numair** [comment]
Thanks, this is super helpful.  Hopefully someone else will benefit from this information in the future...
