### ISSUE TITLE
ORM for caching structs in Redis

### ISSUE THREAD

**Issue by rippaio** [garyburd/redigo#219]
Do you have a suggestion for storing structs in Redis through redigo?  Right now we just use the HMSET/GETALL, but it seems like there should be a more framework-y way to achieve that.  

Any suggestions would be appreciated!

P.S. I love your go-pg package!

**Comment by garyburd** [comment]
Encode the structs to a []byte using [encoding/gob](https://godoc.org/encoding/gob). Store the []byte as a [Redis string](https://redis.io/topics/data-types#strings).  It's a few lines of code. No framework needed.
