### ISSUE TITLE
Time out settings for PubSubConn.recieve

### ISSUE THREAD

**Issue by tianxiaoliang** [garyburd/redigo#221]
If there is no message for topic,the receive function will forever hang in there,How can I stop it?
I write a ws server to let client subscribe topic from redis,if the client closed, the connection between ws server and redis will forever hang,if no message come.

component relation is below
ws client->ws server->redis

**Comment by garyburd** [comment]
Follow [the example in the documentation](https://godoc.org/github.com/garyburd/redigo/redis#example-PubSubConn) for exiting the receive loop.

- Unsubscribe the Redis connection when the websocket connection is closed.
- Exit the receive loop when the subscription count is zero.
