### ISSUE TITLE
Custom Timeouts

### ISSUE THREAD

**Issue by malandrew** [garyburd/redigo#223]
Currently, readTimeout and writeTimeout are set for all of the connections for the whole pool on Dial(). 

We have some commands which are greater priority and for which we can tolerate a greater timeout value. Currently, the timeout is set on Send(), Flush(), Recieve() and Do() on the private net.Conn object. 

I'd like to add the following two functions to the redis.Conn interface{}:

```
type Conn interface {
    AddWriteTimeout(timeout time.Duration)
    AddReadTimeout(timeout time.Duration)
}
```

internally, each function would just check if timeout is non-zero and if it is, it would get the net.Conn object and add an additional timeout. Would this patch be accepted? Do you have any alternative solutions for allowing a greater timeout for some commands than others?

**Comment by garyburd** [comment]
What are the drawbacks of setting the timeout to the largest value needed for all commands?

**Comment by malandrew** [comment]
@garyburd we're using redis as a write-through cache. we want the read commands to fail fast when redis is overloaded and have the reads that timeout to go to our persistent store. 

In our use case, 150ms timeout for write transactions with a retry is fine as it guarantees that the data is there for read transactions. If the writes fail, any reads against that data will fail and we are guaranteed to waste one network round-trip before falling back to our persistent store.

The reads on the other hand we want to be something like 75ms with at most 1 retry, for an upper limit of about 150ms. If it takes longer than that, we can serve the fraction of small fraction of reads that timeout more quickly from our persistent store (Cassandra). This also leaves room to optimistically query Cassandra simultaneously on the retry and return whichever read returns first.

Furthermore, our write commands are 4 commands pipelined using Send(), Flush() and Receive(), which means a retry is a bunch more expensive, so if we increase the likelihood of success with a longer timeout, we reduce load on redis.

Overall, the goal is to minimize absolute latency and latency variability for reads.

The other alternative I've considered is having two or more connection pools for the different use cases. Unfortunately, that's going to require a fair amount of refactoring to support. It would also require us to close all the existing connections in a pool when dynamically configuring/adjusting the timeouts in production without a restart since the timeouts are set in the Dial() function when the net.Conn is established.

**Comment by garyburd** [comment]
Because connections are not usable after a timeout, you will probably get better results by implementing timeouts in the application.

The timeout feature is intended to detect dead servers, not for application logic.

**Comment by garyburd** [comment]
Here's a rough sketch on how to implement the feature at the application level.  

    // op specifies input and output for GET. Adjust as needed for whatever your
    // read command is.
    type op struct {
        key  string
        result chan []byte
    }

    // This sketch uses package level variables for simplicity.  The real code should
    // define a type for the state required by the reader and writer.
    var (
        c         redis.Conn
        requests  = make(chan op)
        responses = make(chan op, 100) // channel size specifies number of requests in flight.
    )

    func init() {
        go reader()
        go writer()
    }

    func writer() {
        for op := range requests {
            c.Send("GET", op.key)
            if err := c.Flush(); err != nil {
                // handle error. 
            }
            responses <- op
        }
    }

    func reader() {
        for op := range responses {
            b, err := c.Receive()
            if err != nil {
                // handle error
            }
            op.result <- b
        }
    }

    func get(key string) []byte {
        t := time.NewTimer(timeout)
        op := op{key: key, done: make(chan []byte, 1)}
        select {
        case requests <- op:
        case <-t.C:
            // timeout sending to reader, fallback to casandra
        }
        select {
        case b := <-op.result:
             t.Stop()
            return b
        case <-t.C:
            // timeout reading result, fallback to casandra
        }
    }

**Comment by malandrew** [comment]
@garyburd Merci.
