### ISSUE TITLE
Official support for Go(lang) 1.3 dropped?

### ISSUE THREAD

**Issue by andygrunwald** [garyburd/redigo#224]
In my travis ci tests i still include golang 1.3.
Today i saw that Go(lang) 1.3 is not working anymore. See my build here: https://travis-ci.org/andygrunwald/simple-webserver/jobs/188265055

In the [.travis.yml](https://github.com/garyburd/redigo/blob/master/.travis.yml) i saw that Golang 1.3 was removed in September. See https://github.com/garyburd/redigo/commit/9c474d0715937065f7e5b9f8d724a72ba55763e7#diff-354f30a63fb0907d4ad57269548329e3

**Question**: Is the official support for Golang 1.3 dropped?

I am not running golang 1.3 in production. Just wanted to raise this question to create awareness.
Maybe it make sense to add the minimum supported golang version into the README, because this is a widely used library.

**Comment by garyburd** [comment]
Yes, support for 1.3 was dropped.
