### ISSUE TITLE
Found unexcepted  Release  of redis connection from pool!

### ISSUE THREAD

**Issue by myafeier** [garyburd/redigo#226]
client.go:114: RecoveredErrorOf:%v,Cid:runtime error: invalid memory address or nil pointer dereference18
<img width="1250" alt="source" src="https://cloud.githubusercontent.com/assets/6135923/21705579/c7ecfc28-d3fb-11e6-93ef-129f396963e9.png">

**Comment by garyburd** [comment]
Please post the stack trace.
