### ISSUE TITLE
Add reply helper functions for GEO commands

### ISSUE THREAD

**Issue by garyburd** [garyburd/redigo#230]
Add [reply helper functions](https://godoc.org/github.com/garyburd/redigo/redis#hdr-Reply_Helpers) for the GEO commands. 

Note: Redigo supports all GEO commands. This issue is about adding convenience functions for working with GEO command results.

**Comment by crackerplace** [comment]
@garyburd I would be interested to work on this feature.

**Comment by garyburd** [comment]
@crackerplace Go for it.
