### ISSUE TITLE
It favours new connection instead of old connections

### ISSUE THREAD

**Issue by ustcyue** [garyburd/redigo#233]
In redis/Pool.go, it always take idle connections from front of List and push the updated connection back into front. When request rate is fluctuating, it will result in lots of unnecessary reconnections. Maybe it's better to take from front and insert into back or vice versa.

**Comment by garyburd** [comment]
Pools shrink by design. Increase the [IdleTimeout](https://godoc.org/github.com/garyburd/redigo/redis#Pool.IdleTimeout) to reduce reconnnections.
