### ISSUE TITLE
suspicious code in fatal func

### ISSUE THREAD

**Issue by rayzyar** [garyburd/redigo#235]
https://github.com/garyburd/redigo/blob/09ea42b08e22e013cb885ad630047e8d41935f81/redis/conn.go#L291
it's checking if c.err == nil { /.../ }
however seems all calls to c.fatal use a non-nil err

Looks like something is wrong with the logic here ?

**Comment by garyburd** [comment]
The expression test the field c.err, not the argument to the function.
