### ISSUE TITLE
Hanging go routines waiting for connection pool. 

### ISSUE THREAD

**Issue by tameem92** [garyburd/redigo#236]
Hello, 

I am currently using the redigo library for my project where i create a redis pool and use it through out the app. The problem i am seeing is that after a certain amount of time all go routines get hung waiting on getting a connection from the connection pool. Here is the code being used for the pool and how its being used: 

Using:
	c := redisPool.Get()
	defer c.Close()

```
	return &redis.Pool{
		MaxIdle:     10,
		MaxActive:   150,
		Wait:        true,
		IdleTimeout: 240 * time.Second,
		Dial: func() (redis.Conn, error) {
			c, err := redis.Dial(redisProtocol, redisServer)
			if err != nil {
				return nil, err
			}
			if len(redisPassword) > 0 {
				if _, err := c.Do("AUTH", redisPassword); err != nil {
					c.Close()
					return nil, err
				}
			}
			return c, err
		},
		TestOnBorrow: func(c redis.Conn, t time.Time) error {
			_, err := c.Do("PING")
			return err
		},
	}

```

Here are some stack traces: 

```
"goroutine 2311260 [semacquire, 21 minutes]:\r\n"
"sync.runtime_notifyListWait(0xc42020d490, 0x1e3)\r\n"
"\t/usr/local/go/src/runtime/sema.go:267 +0x122\r\n"
"sync.(*Cond).Wait(0xc42020d480)\r\n"
"\t/usr/local/go/src/sync/cond.go:57 +0x80\r\n"
"github.com/garyburd/redigo/redis.(*Pool).get(0xc42026e280, 0x50, 0x0, 0x0, 0x0)\r\n"
"\t/go/src/github.com/garyburd/redigo/redis/pool.go:295 +0x576\r\n"
"github.com/garyburd/redigo/redis.(*Pool).Get(0xc42026e280, 0x0, 0x0)\r\n"
"\t/go/src/github.com/garyburd/redigo/redis/pool.go:177 +0x2f\r\n"
"main.(*User).isThrottled(0xc4213b5020, 0x16f56100)\r\n"

"goroutine 2310989 [semacquire, 21 minutes]:\r\n"
"sync.runtime_notifyListWait(0xc42020d490, 0x12e)\r\n"
"\t/usr/local/go/src/runtime/sema.go:267 +0x122\r\n"
"sync.(*Cond).Wait(0xc42020d480)\r\n"
"\t/usr/local/go/src/sync/cond.go:57 +0x80\r\n"
"github.com/garyburd/redigo/redis.(*Pool).get(0xc42026e280, 0x50, 0x0, 0x0, 0x0)\r\n"
"\t/go/src/github.com/garyburd/redigo/redis/pool.go:295 +0x576\r\n"
"github.com/garyburd/redigo/redis.(*Pool).Get(0xc42026e280, 0x0, 0x0)\r\n"
"\t/go/src/github.com/garyburd/redigo/redis/pool.go:177 +0x2f\r\n"
"main.(*User).isThrottled(0xc420a59020, 0x19a66600)\r\n"
```

Do you have any insight on this issue? In one of the projects i got around it by increasing MaxActive but i am working on a high rpm project currently and every few hours or minutes i keep running into this issue and my web server keeps getting hung. Thanks.

**Comment by garyburd** [comment]
The goroutines are blocked waiting for the application to return connections to the pool.

**Comment by tameem92** [comment]
Hi, 

Thanks for the quick response. Every where in the application we get the pull with the following snippet: 

```
c := redisPool.Get()
defer c.Close()
```

There is always a defer c.Close() to return the connections to the pool. The application should be returning connections to the pool, otherwise i would see this happen consistently after some requests. But it happens randomly. 

The defer c.Close() should be enough for the application to always return the connections right?

**Comment by garyburd** [comment]
The `defer c.Close()` is enough to return the connection to the pool.

Does the application get more than one connection per goroutine?

**Comment by tameem92** [comment]
I have one connection from redis per function throughout the app. There are cases where the child function also calls for a connection but i don't see that being a problem because they both defer within the scope of that function . e.g. 

```
func function1() {
  c := redisPool.Get()
  defer c.Close()
 
  function2()
}

func function2() {
  c := redisPool.Get()
  defer c.Close()
}
```

**Comment by garyburd** [comment]
That's the issue. Consider this scenario:

- 150 (pool MaxActive) goroutines call `redisPool.Get()` in `function1` and sleep before calling `function2`.
- The goroutines exit sleep and call `function2`.   

The 150 goroutines will block forever on the call to `redisPool.Get()` in `function2`.

**Comment by tameem92** [comment]
Ahhhhh. That makes sense.Thanks a lot for your help.
