### ISSUE TITLE
unix socket domain

### ISSUE THREAD

**Issue by fbbin** [garyburd/redigo#238]
Ask questions at https://stackoverflow.com/questions/ask?tags=go+redis
how can I use the unix socket domain (xxx.socket) to connect the redis server

**Comment by garyburd** [comment]
To connect using a Unix socket, configure Redis to listen on a Unix socket using the unixsocket parameter in redis.conf. On the client, [dial](https://godoc.org/github.com/garyburd/redigo/redis#Dial) with network "unix" and the path specified in redis.conf.
