### ISSUE TITLE
Dial with default host is failing on Windows

### ISSUE THREAD

**Issue by muly** [garyburd/redigo#240]
`redis.Dial` with default host is failing on Windows. _Note: I found a similar bug reported [golang _net_ standard library](https://github.com/golang/go/issues/15216), but that looks to be resolved._ 

**NOT working**
`redis.Dial("tcp", ":6379")`
_error message:_ `dial tcp :6379: connectex: The requested address is not valid in its context.`

**working**
`redis.Dial("tcp", "localhost:6379")`

**My environment:** 
```
$ go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\gows
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
```

**Comment by garyburd** [comment]
Redigo passes the address directly to net.Dial.  Any fix should be in net.Dial.

**Comment by muly** [comment]
thanks for taking time to respond.
