### ISSUE TITLE
proposal: in-memory Conn implementation, for stub reasons

### ISSUE THREAD

**Issue by GlenDC** [garyburd/redigo#244]
Currently there is no community driven Golang stub for redis. It is however useful for quick testing, without requiring an external server to run.

For now my colleague started an implementation in a repo of ours, as can be seen here: https://github.com/g8os/blockstor/blob/master/nbdserver/stubs/redis.go

However, this implementation is far from complete. It lacks for example all the pipeline features, such that the behavior of the `Send` method and the `MULTI`+`EXEC` commands is wrong. On top of that it lacks the benefits of a community-driven library such as redigo, which gets a lot more usage, reviews and contributions, which would guarantee the quality of the in-memory (stub) implementation.

We would be willing to push the initial version forward, as a more completed form of the version linked above. But first I would like to here your opinions on this proposal.

The goal is simple: have a in-memory (stub) implementation, which is feature-complete, fast yet simple, without deviating from the normal expected behavior.

**Comment by GlenDC** [comment]
Thinking about this more, I do wonder how feasible (and perhaps even desired) this really is. The "EVAL" command is for example a pretty big command to have to support. It requires the implementation to evaluate LUA Scripts as well. Which starts to get really insane. As far as I know, there isn't even a LUA Interpreter for Golang available to start with.

**Comment by garyburd** [comment]
An in-memory implementation of Redis is outside the scope of this project. As you noted, it's a big project.
