### ISSUE TITLE
expose idle conn count in the conn pool

### ISSUE THREAD

**Issue by mbyczkowski** [garyburd/redigo#251]
I've been trying to figure out a sweet spot for the size of conn pool, and so I've been monitoring `ActiveCount` on my servers. Given that there are `MaxIdle` and `MaxActive` options, I thought that maybe exposing `IdleCount` be a good idea?

Happy to submit a PR (see https://github.com/garyburd/redigo/compare/master...mbyczkowski:master for changes).

As a side note, it seems to me that `ActiveCount` actually reflects all the currently open connections in the pool (including the idle ones). If that's so, maybe it would be more accurate to call it `OpenCount`?

**Comment by garyburd** [comment]
Please submit the PR.  

Renaming ActiveCount is not possible because it this change may break existing applications.

**Comment by mbyczkowski** [comment]
thanks @garyburd!

Good point about the breaking change. We could modify the doc though to say `ActiveCount returns the number of open connections in the pool.` instead of `ActiveCount returns the number of active connections in the pool.`.

**Comment by garyburd** [comment]
How about this?

> ActiveCount returns the number of connections in the pool. The count includes connections idle connections and connections in use.

**Comment by mbyczkowski** [comment]
Sounds good to me.
(I assume there was an accidental typo in your example and you meant the 2nd sentence to read `The count includes idle connections and connections in use.`)

**Comment by garyburd** [comment]
Yes, typo.
