### ISSUE TITLE
Closing all connection in pool (active+idle)

### ISSUE THREAD

**Issue by tkpdgun** [garyburd/redigo#254]
Hi, I'm just wondering if redigo library can close all connection. because after I called `pool.Close()`, clients still remain on redis client list.
based on this part it only close idle connection, meanwhile after I do `pool.Close()` and then calling `pool.IdleCount()` will return 0 (but `pool.ActiveCount()` show N numbers)
```
func (p *Pool) Close() error {
	p.mu.Lock()
	idle := p.idle
	p.idle.Init()
	p.closed = true
	p.active -= idle.Len()
	if p.cond != nil {
		p.cond.Broadcast()
	}
	p.mu.Unlock()
	for e := idle.Front(); e != nil; e = e.Next() {
		e.Value.(idleConn).c.Close()
	}
	return nil
}
```
my purpose:
I want to add circuit breaker on my go apps, so when it detects connection error. I want to force close all connection regardless its state and recreate new pool. (considering someone forget call `c.Close()`, connection will remain there after recreating)

can I do this? or maybe you have suggestion

thank you

**Comment by garyburd** [comment]
Write a Conn implementation that delegates all calls to an underlying Conn.  The Close method should also remove the underlying connection from a collection of open connections.

Write a [dial function](http://godoc.org/github.com/garyburd/redigo/redis#Pool.Dial) that dials a connection to the server, adds the connection to the collection of open connections and returns the connection wrapped with the type described in the previous paragraph.

Force close all connections to the server using the collection maintained by the dial function and the Close method.

An alternate approach for protecting the server from a connection leak is to set [MaxActive](http://godoc.org/github.com/garyburd/redigo/redis#Pool.MaxActive) to a value that's larger than the expected number of connections.

**Comment by tkpdgun** [comment]
I think the first approach is good, since it works like idle Conn collection.

thanks for the tip
