### ISSUE TITLE
Efficiency issues when connecting to an external redis host

### ISSUE THREAD

**Issue by chenzhengit** [garyburd/redigo#255]
redis-benchmark -h 172.16.13.21 -p 6378 -q -d 100  -c 500 -n 10000
PING_INLINE: 16207.46 requests per second
PING_BULK: 18115.94 requests per second

=============================================
BUT:
func ping() (err error) {
	r := REDISPOOL.Get()
	defer r.Close()

	if _, err = r.Do("PING"); err != nil {
		return
	}
	return
}

----tps---- 642
----tps---- 751
----tps---- 723
----tps---- 1028
----tps---- 752

so,It's Inefficient  when connecting to an external redis host

**Comment by garyburd** [comment]
Show the complete program including the configuration of the pool.

**Comment by garyburd** [comment]
Closing because no response from OP in 16 days.
