### ISSUE TITLE
Unable to connect to RedisCloud on Heroku due to too many colons in address

### ISSUE THREAD

**Issue by joelpresence** [garyburd/redigo#257]
Hi,

Awesome redis client, thanks for making this available!

We are trying to use RedisCloud on Heroku.  The addon is provisioned and provides a URL like:

```
redis://user:password@a1.a2.a3.ec2.cloud.redislabs.com:port
```

This is a perfectly valid URL and we are able to connect to it using redis cli, and redis clients in Ruby and other languages.

Go seems to barf on this url for some reason.  I have tried adding `[]` around parts of it but I just can't make it work.

Is there any way around this?  I need to deploy to prod today and all my tests pass locally but now I can't contact RedisCloud using this URL in Go (I can contact it using other languages, so the issue lies with either redigo or go).

Can I reformat this url somehow?  Or can I parse it and pass in some struct with parts split out?

I don't want to monkey with this url because RedisCloud could legimately change it and we want to pick up the new url ourselves.

Any help would be hugely appreciated!  :-)

Thanks!

**Comment by garyburd** [comment]
What is the error returned from dial?

**Comment by joelpresence** [comment]
Thanks for the quick response @garyburd !  :-)

The error is: `"dial tcp: address redis://user:password@a1.a2.a3.ec2.cloud.redislabs.com:port: too many colons in address`.  This seems to come from [ipsock.go](https://golang.org/src/net/ipsock.go).

The url above is not the real url - I redacted the password and exact host name for security, but the format is exactly the same.

Any ideas?

**Comment by garyburd** [comment]
The string "port" is not a valid port number.

**Comment by joelpresence** [comment]
@garyburd - I know.  I was just using it as an example.  The actual port is an integer, so the real url is something like `redis://user:password@a1.a2.a3.ec2.cloud.redislabs.com:45678` but I used `port` to illustrate that it was a port that I had redacted for security reasons.  :-)

Does that help?

**Comment by garyburd** [comment]
The error is returned by net.SplitHostPort. I cannot reproduce the error. See https://play.golang.org/p/ILief9R9kJ.

**Comment by joelpresence** [comment]
I can reproduce it every time using the following code:

```
func NewRedisConnectionProviderPool(redisUrl string) *RedisConnectionProviderPool {
	pool := &redis.Pool{
		MaxIdle:     100,
		IdleTimeout: 60 * time.Second,
		Dial:        func() (redis.Conn, error) { return redis.Dial("tcp", redisUrl) },
	}
	return &RedisConnectionProviderPool{Pool: pool}
}

// redisUrl := redis://user:password@a1.a2.a3.ec2.cloud.redislabs.com:45678
```
It  fails with this every time.  Any ideas?

**Comment by garyburd** [comment]
The second argument to Dial is a an address, not a URL. 

Call [DialURL](http://godoc.org/github.com/garyburd/redigo/redis#DialURL) to use a URL.

**Comment by joelpresence** [comment]
@garyburd thanks, this works.  I don't know why I didn't see `DialURL` but it does now work with that.  Sorry, I should have RTFM, I apologize for wasting your time.  Thanks again!  :-)
