### ISSUE TITLE
How do I cross compile redigo ?

### ISSUE THREAD

**Issue by balajcse** [garyburd/redigo#263]
Ask questions at https://stackoverflow.com/questions/ask?tags=go+redis

I am new to go language.  I found redigo suits my requirement and I am not able to compile this library locally. any help will appreciate

**Comment by elithrar** [comment]
What have you tried?

This library doesn’t have any C bindings and thus regular Go
cross-compilation applies.

You don’t need to cross-compile the library directly; it will be compiled
for the target architecture when you compile the project that imports it.
