### ISSUE TITLE
SyncConn and DialSyncTimeout is gone

### ISSUE THREAD

**Issue by y0908105023** [garyburd/redigo#264]
Ask questions at https://stackoverflow.com/questions/ask?tags=go+redis
the new version,can't find out the DialSyncTimeout && SyncConn

**Comment by garyburd** [comment]
SyncConn and DialSyncTimeout were never part of this package.

**Comment by y0908105023** [comment]
thaks for your reply,i had found the solution to this problem，SyncConn && DialSyncTimeout  is defined by our developper.
