### ISSUE TITLE
Error when reply is a mix of both byte array and int64 in reply.Strings function

### ISSUE THREAD

**Issue by kpachhai** [garyburd/redigo#269]
I noticed there is currently a bug in reply.Strings function in reply.go.
So, I was trying to grab the results of: 
`redis-cli -p $port latency latest`
1) 1) "command"
   2) (integer) 1500857214
   3) (integer) 250
   4) (integer) 1003

using Strings function(in reply.go) but it doesn't work. I investigated into what was going on further and found out i was getting the error that says:
`redigo: unexpected element type for Strings, got type int64`

I was confused by this so i tried debugging further and found that it was complaining because when i do the following in my code:
`if latencyFullResult, latencyErr := c.Do("LATENCY", "LATEST"); latencyErr == nil && latencyFullResult != nil {`
`        tempVal, _ := latencyFullResult.([]interface{})`
`        if len(tempVal) > 0 {`
`            latencyResult := tempVal[0]`
`            log.Println(latencyResult)`
`            if latency, err := redis.Strings(latencyResult, latencyErr); err != nil {`
`                log.Printf("redis err: %s", err)`
`            } else {`
`                // do something`
`            }`
`        }`
`    }`

I found out the value that i was getting in latencyResult was:
`[[99 111 109 109 97 110 100] 1500857214 250 1003]`

And because the output is a mix of both byte array and int64 and because Strings function is not able to handle this case at the moment, i was getting that error. 

Sorry about all the weird formatting of the code you see here. Still a noob when it comes to posting an issue in github.

**Comment by garyburd** [comment]
Yes, the Strings function is not appropriate for this command.  Use Scan:

     var name string
     var t, latest, max int64
     if _, err := redis.Scan(reply, &name, &t, &latest, &max); err != nil {
        // handle error
    }

**Comment by kpachhai** [comment]
Thanks. Totally missed that. Still a beginner at using this package. Thanks for the quick reply!
