### ISSUE TITLE
Write Broken pipe

### ISSUE THREAD

**Issue by nsagnett** [garyburd/redigo#274]
Hi there, 

Can you tell me why this error happen sometimes ?
`write tcp <ip> -> 127.0.0.1:6379: write: broken pipe`

You can check my configuration pool:
```
&redis.Pool{
		MaxIdle:     100,
		IdleTimeout: 240 * time.Second,
		Dial: func() (redis.Conn, error) {
			c, err := redis.Dial("tcp","localhost:6379")
			if err != nil {
				c.Close()
				return nil, err
			}
			return c, nil
		},
	}
```
thanks for reply :)

**Comment by garyburd** [comment]
The connection was dropped. Check the server logs for possible cause.

**Comment by nsagnett** [comment]
After some others tests, conf was not the best for my usage. It works like a charm.

Thanks :)
