### ISSUE TITLE
The Send function breaks my struct. 

### ISSUE THREAD

**Issue by itzikbenh** [garyburd/redigo#280]
I have a struct in this format 
```go

type Reply struct {
  Topic   string `redis:"topic" json:"topic"`
  Ref string `json:"ref"`
  Payload struct {
      Status string `json:"status"`
      Response map[string]interface{} `json:"response"`
  } `json:"payload"`
}
```
I fill it with JSON data that I get back from the websocket, but when it gets passed to the Send function I get back a byte it seems and when I convert it to string data is missing. 
I assume the Scan function breaks it, but I can't find anyway to avoid this. 

I realize that this might sound like a regular question, but there's no explanation anywhere on this.

If it helps this is the Redis code - https://play.golang.org/p/TOzJuvewlP
On line 161 I "writeToRedis" in which I use the Send function. 
On line 55 I'm waiting for to receive a message. 

I saw in the documentation that there's a scanStruct, but how can I use it? All the examples assumes a basic string. Is this data structure not supported?

Just to make it clear, this is what I get and what I'm supposed to get
```js
//Get
"{{spr_reply sketchpad map[] 1} {ok map[success:Joined successfully]}}"
//Supposed to get
{event: "spr_reply", topic: "sketchpad", ref: "45", payload: {status: "ok", response: {}}}
```

**Comment by garyburd** [comment]
The `Reply` type is converted to a Redis bulk string using `fmt.Sprintf(v)` (see documentation [here](https://godoc.org/github.com/garyburd/redigo/redis#hdr-Executing_Commands)). That's not useful for this type.

I suggest encoding the value to a `[]byte` using the [encoding/json](http://godoc.org/encoding/json) or [encoding/gob](http://godoc.org/encoding/gob) packages.  Publish the `[]byte` value.

The application should receive the response from the PUBLISH command.  Perhaps the application is already doing this, but I didn't see it in my quick skim through the code.

**Comment by itzikbenh** [comment]
Thank you very much :), it was an easy fix apparently. I Marshal it before I publish and then Unmarshal when I write back JSON. 
And yes, it does it here:
```go
//The solution
p, err := json.Marshal(data)
if err != nil {
	return errors.Wrap(err, "Unable to encode message to json")
}
if err := conn.Send("PUBLISH", Channel, data); err != nil {
	return errors.Wrap(err, "Unable to publish message to Redis")
}
```

**Comment by garyburd** [comment]
The application should receive the response from PUBLSH.  Change conn.Send to conn.Do.
