### ISSUE TITLE
Receive cancelation when we have no data in subscribed channel

### ISSUE THREAD

**Issue by gen1us2k** [garyburd/redigo#286]
Hey there. Thank you for a such great library.
I'm wondering. Is there any way to stop listening a channel which we subscribed to?
I have this scenario:
1. Client connects to websocket server
2. We spawn listener to redis channel
3. We run infinite for loop with Receive method
4. We wait for data from redis channel
5. Client disconnects from websocket server
6. Goroutine still alive with listening to redis.

The reason why it blocks is Receive method waits for data and locked connection. When we use readTimeouts it works. But is there any other way to achieve Receive cancelation?

**Comment by elithrar** [comment]
You could implement a “done” channel on the background worker: when the WS
is terminated, the server will then:

1. remove the client connection from its client data structure
2. this should also send a done message to the Redis worker goroutine,
which can then be closed.

If you can share the code surrounding how you spawn that Redis subscribing
goroutine I can potentially give more pointed advice.

**Comment by gen1us2k** [comment]
https://gist.github.com/gen1us2k/e890a0d67d08ccf67b6afcd059053924

**Comment by gen1us2k** [comment]
I have a "done" channel named stopSubscription

**Comment by gen1us2k** [comment]
But it works when I receive data in channel I'm subscribed to. When I don't receive any messages it blocks

**Comment by gen1us2k** [comment]
ReceiveTimeout(time.Duration) API will be very useful for such case

**Comment by garyburd** [comment]
The [PubSubConn example](https://godoc.org/github.com/garyburd/redigo/redis#example-PubSubConn) shows one approach for exiting the goroutine:

    - Unsubscribe all channels when done
    - Exit the receive loop when subscription count is zero

The code in the gist [unsubscribes all channels](https://gist.github.com/gen1us2k/e890a0d67d08ccf67b6afcd059053924#file-gistfile1-txt-L37).  

Add this code to exit the goroutine:

    case redis.Subscription:
        grpclog.Infof("redis %s to %s, subscriptions number: %d", v.Kind, v.Channel, v.Count)
        if v.Count == 0 {
             return
       }

**Comment by garyburd** [comment]
The proposed `ReceiveTimeout` does not remove the requirement that the application unsubscribe the connection before returning the connection to the pool.  Unsubscribe the connection is sufficient to handle this case.
