### ISSUE TITLE
go test failed in ubuntu-14.04

### ISSUE THREAD

**Issue by mindlesslcc** [garyburd/redigo#290]
Ask questions at https://stackoverflow.com/questions/ask?tags=go+redis
ubuntu 14.04  go1.9 
go test failed and output is as below

--- FAIL: TestWaitPoolCommandError (0.25s)
        pool_test.go:537: ERR wrong number of arguments for 'ping' command
--- FAIL: TestWaitPoolDialError (0.25s)
        pool_test.go:576: expected dial error or nil, got ERR wrong number of arguments for 'ping' command
--- FAIL: TestPushed (0.00s)
        pubsub_test.go:108: Ping("hello") = ERR wrong number of arguments for 'ping' command, want {hello}
        pubsub_test.go:108: Send("PING") = ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / QUIT allowed in this context, want {}
FAIL
exit status 1
FAIL    github.com/garyburd/redigo/redis        1.089s

**Comment by garyburd** [comment]
The tests require Redis version 3.2 or later.  The package works with older versions of Redis.
