### ISSUE TITLE
Error with Ints and Int64s functions

### ISSUE THREAD

**Issue by herkyl** [garyburd/redigo#291]
After [this update](https://github.com/garyburd/redigo/commit/200b674d7407b7ff1b36b46f1cd853180d5e5298) `Ints` function is not working for me anymore. The `Int64s` function has the same issue.

```go
func main() {
	_, err := redis.Ints([]interface{}{4, 5}, nil)
	log.Error(err) // redigo: unexpected element type for Ints, got type int
}
```

This happens when I use `Ints` in conjunction with `MULTI` + `SCARD`

```go
rc.Send("MULTI")
for _, c := range array {
	rc.Send("SCARD", fmt.Sprintf("rediskey:%s:data", c))
}

ints, err := redis.Ints(rc.Do("EXEC"))
```

**Comment by garyburd** [comment]
Yikes.  This is not a scenario that I ever considered. Fix is coming.

**Comment by herkyl** [comment]
Works 👍
