### ISSUE TITLE
Sorry but I need to ask int64s here

### ISSUE THREAD

**Issue by unisqu** [garyburd/redigo#299]
//can save but can't read int64s value? what is wrong below? pls help. thx. i cant find any example usage online. i dont have stackoverflow account. 

package main

import (
        "fmt"
        "time"
        "github.com/garyburd/redigo/redis"

)
var pool = newPool()

func main() {
        c := pool.Get()
        defer c.Close()
        
        xval := 12334
        yval := "thisisstring"

        timestampvals, err := redis.Int64s(c.Do("HGET", xval, yval))

        if err == nil {
                fmt.Printf("NIL\n")
        }
                fmt.Printf("LENG = %d\n",len(timestampvals))

        for _, timestamp := range timestampvals {
                fmt.Printf("%d , ", int64(timestamp))
        }

        timeNow := int64(time.Now().UTC().Unix())
        timestampvals = append(timestampvals, timeNow)
        fmt.Printf("%d\n", timeNow)

        redis.Int64s(c.Do("HSET", xval, yval, timestampvals))
}

func newPool() *redis.Pool {
        return &redis.Pool{
                MaxIdle: 80,
                MaxActive: 12000, // max number of connections
                Dial: func() (redis.Conn, error) {
                        c, err := redis.Dial("tcp", ":6379") //pls change to 6379. thx
                        if err != nil {
                                panic(err.Error())
                        }
                        return c, err
                },
        } 
}

**Comment by garyburd** [comment]
The error returned from Int64s explains the problem.

**Comment by monicaq** [comment]
You are attempting to read and write slice of int64 to Redis string.  That does not work as the error from Int64s tells you. Decode/encode the slice to []byte using JSON, gob, msgpack or some other codec.
