### ISSUE TITLE
All tagged releases removed

### ISSUE THREAD

**Issue by akshayjshah** [garyburd/redigo#3]
:wave: Thanks for writing such a nice redis client! :wave:

Like much of the Go community, we use a tag-aware dependency manager (`glide`, in our case). That means that we've been relying on your tagged releases in our semver constraints. Unfortunately, somewhere in the force-push mishap, all the tagged releases were removed from this repo.

We'll eventually move over to `github.com/gomodule/redis`, but in the meantime, can you re-push tags here?

**Comment by garyburd** [comment]
Fixed. I apologize for that.

**Comment by akshayjshah** [comment]
No worries - things happen :) Thanks for the quick response!
