### ISSUE TITLE
Pool leaks TCP conn

### ISSUE THREAD

**Issue by cee-dub** [garyburd/redigo#301]
https://github.com/garyburd/redigo/blob/b389d5392e340092642eec4e36754e0280ad1f8e/redis/pool.go#L333

This line does not close the TCP connection, and thus leaks a socket (file descriptor). You can reproduce this by using a `Pool` with more clients doing operations than `MaxIdle` such that dials need to happen often. Eventually, the machine runs out of file descriptors.

**Comment by garyburd** [comment]
The connection is added to the idle list [here](https://github.com/garyburd/redigo/blob/b389d5392e340092642eec4e36754e0280ad1f8e/redis/pool.go#L329).  Connections in the idle list remain open.

**Comment by cee-dub** [comment]
I think that accurately describes the problem. I've hit a case where the idle list grows without bound. Is that the intended behavior? Does `MaxIdle` need to be tuned to a number higher than the concurrent callers of `Pool.Get()`?

**Comment by garyburd** [comment]
Are you saying that you have case where [idle count](https://godoc.org/github.com/garyburd/redigo/redis#Pool.IdleCount) is greater than [max idle](https://godoc.org/github.com/garyburd/redigo/redis#Pool.MaxIdle)?

To avoid excessive dialing, MaxIdle should be tuned to a value greater than the number of concurrent users of the pool.

What's your level of concurrency?

**Comment by cee-dub** [comment]
I didn't debug the value idle count when I was encountering the problem, but concurrency was higher than `MaxIdle`. I appreciate the advice "to avoid excessive dialing, tune MaxIdle to a value greater than the number of concurrent uses of the pool," and I'm wondering if I missed that somewhere in the documentation.

I was caught by surprise that with concurrency higher than `MaxIdle`, new callers would dial rather than reuse an idle connection.

**Comment by garyburd** [comment]
Idle connections are used before dialing a new connection. 

There few reasons why the app may be using a large number of connections:

- The application is leaking connections. The application must close the connection when the application is done with the connection.
- The application holds the connection for longer than necessary.  Don't hold connections during long operations that don't use Redis.
- The application has high concurrency. Typical web applications do not fall in this category. The workaround for this is to multiplex concurrent requests using Send/Flush/Receive.

**Comment by cee-dub** [comment]
I'm doing a bulk load operation, and in the case where I ran into this issue, I was calling the following code at a concurrency of 32 with a MaxIdle of 10.

``` go
c := r.pool.Get()
	_, err := c.Do("HMSET", redis.Args{}.Add(key).AddFlat(data)...)
	c.Close()
```

Using Send to pipeline data into fewer requests/round trips will ease contention on the pool, no question.

Once I adjusted MaxIdle higher than 32 (but just how much higher was run-dependent) my machine ran out of sockets less quickly, or was able to complete a batch without running out.

It is still unclear to me why this program leaks sockets when `Close()` is called after each get, or why the pool codes to dial when there are idle connections available. I'll try to put a small example together to demonstrate.

**Comment by cee-dub** [comment]
"The pool codes to dial" should read "the pool chooses to dial"

**Comment by garyburd** [comment]
I cannot reproduce a leak or failure to use idle connections when running 32 concurrent loops of:

       c := r.pool.Get()
	_, err := c.Do("HMSET", redis.Args{}.Add(key).AddFlat(data)...)
	c.Close()

Please post code that reproduces the problem. Include the pool configuration in the code that you post.

**Comment by garyburd** [comment]
Cannot reproduce.

**Comment by cee-dub** [comment]
I'm also having trouble finding the specific code to reproduce the issue as I saw it. Perhaps there was a subtle timing issue between releasing a concurrency limiter and closing the pool connection used by that function.
