### ISSUE TITLE
Pool should implement an interface

### ISSUE THREAD

**Issue by alecha** [garyburd/redigo#303]
In one of my project, I'd neet to make some unit tests on a component that takes a `redis.Pool` as dependency in the constructor. 

Because of I'd like to mock it, I've created in my code an interface that `redis.Pool` implements but I think that it can be useful to include id in the project

**Comment by garyburd** [comment]
Applications should define the interface that they need for testing.

Many applications can work with `func() redis.Conn` as the pool type. This simple type does not need a name.

There are issues with defining an interface with a snapshot of the current Pool methods.

- When methods are added to the Pool type, yet another interface is needed. See 82e3be52a120eb3d6281038ffdf5bcf8924bbadc for a recent example of adding method.
- Stubbing out the methods not used by the application can require more code than defining the exact interface required by the application.
