### ISSUE TITLE
set read/write timeout for each request

### ISSUE THREAD

**Issue by zhangruiskyline** [garyburd/redigo#307]
I noticed if I set read and write timeout at redis connection pool creation time, somehow the AUTH method took longer so that I need to set the timeout in large value, however, after connection is established. I want to set read/write timeout to short value, is there any way I can set read/write timeout for each request?

**Comment by garyburd** [comment]
The AUTH command is very fast.  It's just a string compare.

How long does the AUTH command take?  How does that compare to the time for the PING command?  What timeout are you setting?

**Comment by garyburd** [comment]
Duplicate of #298

**Comment by garyburd** [comment]
See 2ca15d09f96ce36a2acdef20a2c461ce8b4f2e46.
