### ISSUE TITLE
found DATA RACE when unsubscribe 

### ISSUE THREAD

**Issue by i19** [garyburd/redigo#315]
https://github.com/garyburd/redigo/blob/master/redis/pool.go#L383

and

https://github.com/garyburd/redigo/blob/master/redis/pool.go#L446-L448

since it can be cause error, and can be handled, is it on purpose ?

**Comment by garyburd** [comment]
Does the application call Close and Receive concurrently? 

Connections support one concurrent caller to the Receive method and one concurrent caller to the Send and Flush methods. No other concurrency is supported including concurrent calls to the Do method.

**Comment by i19** [comment]
Yes, it is.

I am using pub/sub to broadcast status to other siblings so that i can make the program stateless. 

Besides, i need different channel for different requests, so the lifecycle of pub/sub for one channel  is not that long. So, when i subscribed from one channel, i need to close it ASAP. 

by the way. I was using the pool. so the `close` is not really close the connection .

**Comment by garyburd** [comment]
Concurrent calls to Close and Receive are not supported. The error is in the application.

**Comment by garyburd** [comment]
The pub/sub example in the documentation shows how to cleanly close a pub/sub connection.
