### ISSUE TITLE
Add SetConnMaxLifetime for pool

### ISSUE THREAD

**Issue by taozle** [garyburd/redigo#317]
Like `SetConnMaxLifetime` in the standard `database/sql` package, we should add this kind of method in redigo which is useful when the redis is behind a proxy like twemproxy.

**Comment by garyburd** [comment]
Does https://godoc.org/github.com/garyburd/redigo/redis#Pool.IdleTimeout do what you need?

**Comment by garyburd** [comment]
Am I correct in assuming that you want this as a Pool feature?

**Comment by taozle** [comment]
I don't think the idle timeout can fix my issue, connections in pool are frequently be fetched and put back, so the connection won't reach the idle timeout.
Yes, i think add a field called `MaxLifetime` in pool can fix my case. after set this field, it will new a goroutine which will periodically check the pool's connection and close the connection  when it serves the `MaxLifetime` time.

**Comment by garyburd** [comment]
Fixed by a7327d8ced8067e916e7e35490522fd0182fa839.

**Comment by taozle** [comment]
Great!
