### ISSUE TITLE
High concurrency scenarios produce a lot of time_wait.

### ISSUE THREAD

**Issue by lnyyj** [garyburd/redigo#318]
system: Linux localhost.localdomain 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

![aaa](https://user-images.githubusercontent.com/20123831/35967888-3e3e4568-0cfd-11e8-8fb7-10b4a6ff6ad7.png)

**Comment by garyburd** [comment]
Describe what the program is doing.  Don't post images.

**Comment by lnyyj** [comment]
Initializing the redis connection pool, each client connects to the server (high concurrency), gets the connection in the pool, then performs the operation, and finally returns to the pool.The scene is simple.
Connections are often created when MaxIdle and MaxActive are not equal.If equal, there is no TIME_WAIT.

**Comment by garyburd** [comment]
Adjust MaxIdle up to reduce number the number of short-lived connections.
