### ISSUE TITLE
Timeout looks like dose not timeout in real application

### ISSUE THREAD

**Issue by zhangruiskyline** [garyburd/redigo#320]
I am setting redigo DialReadTimeout and DialWriteTimeout in some fix number(5ms), but in our application, if I measure the latency of single command like

value, err := redis.String(client.Do("GET", key))

sometimes I still got spike and latency for this single command is much higher than fixed 5ms timeout. do I suppose to get timeout if this Get key takes more than 5ms?

Thanks
Rui

**Comment by garyburd** [comment]
If the response is not read before the read timeout, then an error is returned and the connection is no longer usable. Set the read timeout to a value larger than you expect during normal use.

**Comment by clanstyles** [comment]
I'm also having a lot of timeout issues in production.

Things will start to timeout, ignoring the timeout settings, and then just hang forever. There is no rhyme or reason to it. There is no re-trying the connection, etc..

**Comment by garyburd** [comment]
@clanstyles What are the timeout settings, what are the errors returned, and where is the program stuck when it hangs forever?

**Comment by zhangruiskyline** [comment]
@garyburd sorry I did not quite understand what you mean "If the response is not read before the read timeout, then an error is returned and the connection is no longer usable". you mean after timeout(5ms in my case) the read will return and that particular connection is not available anymore ,even maybe after 30-50ms the value did return?

Also in this case can I measure the redis read access delay like this way?

	redisAccessStart := time.Now()
	value, err := redis.String(client.Do("GET", key))
	redisAccessDuration := time.Since(redisAccessStart)
	util.TrackPerformanceMetric("RedisLatency", float64(redisAccessDuration), opIds)

Also I am running a very delay sensitive application, so I would prefer to set low timeout to let redis access timeout rather than blocking waiting read back in longer time, what is best practice in this manner? can I set timeout in very short value?

Thanks
Rui

**Comment by zhangruiskyline** [comment]
@garyburd Based on your comments

is this the best way to measure real redis latency?  in case of timeout, it will fail after timeout value and return err?


	redisAccessStart := time.Now()
	value, err := redis.String(client.Do("GET", key))
	if err != nil {
		redisAccessDuration := time.Since(redisAccessStart)
		util.TrackPerformanceMetric("RedisLatency", float64(redisAccessDuration), opIds)
	}

**Comment by garyburd** [comment]
The Do method sets the [read deadline](https://godoc.org/net#Conn.SetReadDeadline) on the [underlying network connection])https://godoc.org/net#Conn) before reading the response.  The underlying network connection will return an error when the read does not complete before the deadline.

The connection is no longer usable after the underlying network connection returns an error, including timeout errors.  The connection returns the error from the underlying network connection.

**Comment by zhangruiskyline** [comment]
@garyburd Thanks, so if I am using a connection pool, and one connection get timeout, dose redigo only terminate that particular connection and return back to connection pool? or it will close whole pool and re connect to redis sever by establishing a new pool of connections? I would need to prevent second case in my application

Thanks
Rui

**Comment by garyburd** [comment]
The pool closes the only the connection with the error.

**Comment by zhangruiskyline** [comment]
Just double check again, in theory, the below would measure the redis cache latency, if it is successfully done, it will return read latency, if it time out, it should return timeout set up value, right?

redisAccessStart := time.Now()
value, err := redis.String(client.Do("GET", key))
redisAccessDuration := time.Since(redisAccessStart)
util.TrackPerformanceMetric("RedisLatency", float64(redisAccessDuration), opIds)

@garyburd what I get from you is I need to set timeout in each command
redis.String(client.Do("GET", key))

If I only set the timeout value in redis.DialReadTimeout during dial stage, is that good enough?

Thanks
Rui

**Comment by garyburd** [comment]
The snippet measures the duration of whatever happens in `redis.String(client.Do("GET", key))`, be it a timeout or success.

The documentation for [ConnWithTimeout](https://godoc.org/github.com/garyburd/redigo/redis#ConnWithTimeout) explains the scenarios where the application might want to specify the timeout per command.  A simple "GET" is not one of those scenarios.

**Comment by zhangruiskyline** [comment]
Thanks @garyburd, as I indicated, the performance metric I got from the code snippet

redisAccessStart := time.Now()
value, err := redis.String(client.Do("GET", key))
redisAccessDuration := time.Since(redisAccessStart)

could get some value much longer than timeout value. in my case, I set timeout as 5ms, but in my metrics especially in 99 percentile, sometime it could measure as long as 70-80ms.

should I suppose to get metric no more than 5ms?

Thanks
Rui

**Comment by garyburd** [comment]
If there's a timeout, than the duration of the call to `redis.String(client.Do("GET", key))` will be greater than the timeout value.

**Comment by zhangruiskyline** [comment]
Hi @garyburd but I expect "value, err := redis.String(client.Do("GET", key))" to return if timeout happen. so it won't block for too long. but according to your comment, if there is timeout, the underline redis lib return timeout error, but the redis.String(client.Do("GET", key)) will still blocking waiting some longer period than timeout

is there anyway I can ensure this particular action redis.String(client.Do("GET", key)) won't blocking waiting for more than timeout value?

Thanks
Rui

**Comment by garyburd** [comment]
> but I expect "value, err := redis.String(client.Do("GET", key))" to return if timeout happen.  

It does.

> but the redis.String(client.Do("GET", key)) will still blocking waiting some longer period than timeout

I said that the time to execute `redis.String(client.Do("GET", key))` is greater than the read timeout in the case of a timeout, not that it blocks.  

The Do method sets a write deadline, writes the command arguments to the network connection, sets the read deadline and reads the response from the network connection.  The read with deadline is just one part of this.

**Comment by zhangruiskyline** [comment]
Thanks, so the overall duration of  `redis.String(client.Do("GET", key))` is roughly` writetimeout + readtimeout `? in my case, both is 5ms so I expect to have 10ms or a little bit more for overall duration. right? but I have observed sometimes it could go into 30-60ms, though in rare situation. what could cause this particular one line instruction to be executed much longer than expected?

Thanks
Rui

**Comment by zhangruiskyline** [comment]
A follow up question, looks to me `redis.String(client.Do("GET", key))` is not atomic and is there any chance that between write command into network connection and readback, another goroutine is scheduled and extends the instruction latency?

Thanks
Rui

**Comment by garyburd** [comment]
The issue tracker is for reporting issues with the package. It's not a support forum. Based on the discussion so far, I don't see any evidence there's an issue with the package.
