### ISSUE TITLE
Could you change golang.org/x/net/context to standard library context?

### ISSUE THREAD

**Issue by Codefor** [garyburd/redigo#322]
golang.org/x/net/context is slow in some areas, China for example.

[package context](https://godoc.org/golang.org/x/net/context)

package context
import "golang.org/x/net/context"

Package context defines the Context type, which carries deadlines, cancelation signals, and other request-scoped values across API boundaries and between processes. **As of Go 1.7 this package is available in the standard library under the name context. https://golang.org/pkg/context.**
`

**Comment by garyburd** [comment]
I used x/net/context to support older versions of Go.  I'll remove support for the older Go versions and see what happens.

**Comment by Codefor** [comment]
You can use go build tags to support different Go versions.

https://github.com/bitly/go-simplejson for example.

It is so easy, just separate to xxx_go19.go  xxx_go10.go and so on.

See: [Build_Constraints](http://golang.org/pkg/go/build/#hdr-Build_Constraints)

**Comment by garyburd** [comment]
You can also view this package for an example of how to use build constraints.

Separating the context dependency to another file requires duplicating pool.get() or splitting the function. I don't like either option.

**Comment by garyburd** [comment]
After writing the previous comment, I realized that I can nicely separate the context dependency by using a local definition of the context.Context interface.  Fixed in a69d19351219b6dd56f274f96d85a7014a2ec34e.
