### ISSUE TITLE
could we pre open/allocation max idle connections when connection pool established?

### ISSUE THREAD

**Issue by zhangruiskyline** [garyburd/redigo#326]
Found out the latency to open a new connection in connection pool is pretty high(instead of grab a closed and return to pool connection). which could cause latency spike once a while.

Do we have a way to pre open/allocation max idle connections when connection pool established(like in dial stage)?

**Comment by garyburd** [comment]
conns := make([]redis.Conn, p.MaxIdle)
    for i := range conns {
         conns[i] = p.Get()
    }
    for _, conn := range conns {
       conn.Close()
   }

**Comment by zhangruiskyline** [comment]
Thanks, so later in application, if we want to use connection from pool, we just need to do `p.Get()` as normal? also dose this requires we have `redis.DialKeepAlive()`

**Comment by garyburd** [comment]
Yes, do p.Get() as normal.  

Read [the documentation for DialKeepAlive](https://godoc.org/github.com/garyburd/redigo/redis#DialKeepAlive). The feature is unrelated to pools.
