### ISSUE TITLE
[suggestion] Provide more friendly API

### ISSUE THREAD

**Issue by Jamesxql** [garyburd/redigo#327]
Refer to the [Python Redis client API implementation](https://github.com/andymccurdy/redis-py)

For example, a string-type API are the following: 
* Get
* Set
* Delete
* Incr
* Decr
* IncrBy
* DecrBy
* IncrByFloat
* Append
* GetRange
* SetRange
* GetBit
* SetBit
* BitCount
* BitOp

Then we can do:
```Go
c, _ := redis.Dial("tcp", "localhost:6379")
s, err := c.Get("skey")
if err != nil {
	log.Fatal(err)
}

fmt.Println(s)
```

The name of the API is the same as the name of the [Redis command](https://redis.io/commands)，this convenient user to find documents.

**Comment by garyburd** [comment]
This change will break implementations of the redis.Conn interface.  No thanks.
