### ISSUE TITLE
Encoding and decoding types

### ISSUE THREAD

**Issue by garyburd** [garyburd/redigo#46]
Redigo supports encoding an decoding of types known to the Redis server (boolean, float, integer, string).  Redigo also encodes arbitrary types using fmt.Sprint. The fallback to fmt.Sprint is not useful and is an accident of the implementation.

Consider one of the following alternatives:

- Encode and decode values using the Go 1.2 encoding interfaces (BinaryMarshaler, TextMarshaler, BinaryUnmarshaler, TextUnmarshaler). Issues: Should binary or text  take precedence? 
- Encode and decode values with a marshaler interface specific to Redigo. The encoding/json and encoding/gob packages define their own interfaces.
- Return an error for unsupported types. Applications should encode and decode values outside of Redigo.

Any change from the fmt.Sprint fallback can break existing uses of Redigo. 

Some notes on time.Time:

- Redis works with two time formats: seconds since the epoch encoded in decimal for the EXPIREAT, LASTSAVE, TIME commands and  milliseconds since the epoch encoded in decimal for the PEXPIREAT command.
- The encoding used by time.Time MarshalBinary and UnmarshalBinary is undocumented.  
- Times are currently encoded (via fmt.Sprint) with the format "2006-01-02 15:04:05.999999 -0700 MST".  Nanoseconds since the epoch, milliseconds since the epoch and RFC3339 are all more useful encodings than the current encoding.

**Comment by stevenh** [comment]
Looks like this is partially for-filled by https://github.com/garyburd/redigo/pull/176
