### ISSUE TITLE
feature request: Internal support for non-data commands

### ISSUE THREAD

**Issue by therealbill** [garyburd/redigo#77]
There are several Redis informational commands such as "info" and it's subcommands (i.e. the sections) and various sentinel commands such as "sentinel master", "sentinel masters", "sentinel slaves". Redigo should offer these results as dedicated commands which return structs of the information.

For example, running the various info commands returns such data as:

```
used_memory:810872
used_memory_human:791.87K
used_memory_rss:2355200
used_memory_peak:810872
used_memory_peak_human:791.87K
used_memory_lua:33792
mem_fragmentation_ratio:2.90
mem_allocator:jemalloc-3.3.0
```

Currently Redigo returns a string of all the data, requiring the consumer to parse the string into values (such as a map or struct). Ideally Redigo would do as other bindings do and return the data already parsed. For example the above could be returned as a Struct. This is a convenience to the consumer of the API, but a very useful one.

There are, however, Redis informational commands which are more than convenience -  consider the Sentinel commands.

The command "sentinel master cache" (where "cache" is the name of a master being monitored by the sentinel). issued in the CLI will return data along the following format:

```
127.0.0.1:26379> sentinel master cache
 1) "name"
 2) "cache"
 3) "ip"
 4) "127.0.0.1"
 5) "port"
... remainder snipped for brevity
```

This is fairly easy to convert, I believe, with ScanStruct. However, it is tedious to define. Some of the fields returned are hyphenated, meaning you have to tag them. Including this in the library via a specific command would greatly increase this use case's simplicity.

However, moving to the command "sentinel masters" you get a list of the above entries:

```
127.0.0.1:26379> sentinel masters
1)  1) "name"
    2) "cache"
    3) "ip"
    4) "127.0.0.1"
    5) "port"
    ...
2) ....
```

This too should be parsed into a Struct by the library. Other sentinel commands have this same pattern. This pattern does not appear to be directly supported by ScanStruct. I've been able to work around it by iterating over the return value of Values(), then calling Values(item_in_list, nil), then calling ScanStruct on that value. Still, this is not a simple path nor is it obvious. It may not even be the more efficient way to do it (still new to Go here), and feels rather ... hacky.

For the Sentinel commands, there is a reason beyond user ease to build this into the library. In order to support Sentinel, and possibly Redis Cluster, the library will need to know this same information in order to select a master to write/read to/from or a collection of slaves to read from.

At an absolute minimum, defining the structs in the library and exporting them for the user to reference would be an improvement. 

As far as the command names I'd start with a suggestion of something like

```
c.SentinelMaster(name string) -> returns a struct representing a MasterEntry
c.SentinelMasters() -> Returns a []MasterEntry
c.Info(section string) -> returns a Struct for the section given, unless "all" is the section in which case a [] of Structs or an InfoAllStruct which contains each section's struct in it.
```

Thoughts?

**Comment by garyburd** [comment]
Applications should parse the fields they need.  The code is simple.

**Comment by DevMH** [comment]
Re: the INFO parse request, given the fragility of section and field names (and the format of both) for Redis INFO responses, a struct may be brittle and ultimately not a great candidate for a general library. Any parsing mechanism will share some risk.

That said, for anyone looking for a quick-and-dirty solution, the following returns a simple map[string]string of the elements returned in an INFO call (minus section headers). Dependencies on /regexp and /strings

<pre><code>
func ParseInfo(str string) map[string]string {
	info := make(map[string]string)
	
	// removing section headers (Redis [3.2.6] format)
	regex,_ := regexp.Compile("# ([a-zA-Z]+)\r\n")	
	str = regex.ReplaceAllString(str,"")
	
	split := strings.Split(str,"\r\n")
	for _,v := range split {
		kvp := strings.Split(v,":")
		if len(kvp) == 2 {
			info[kvp[0]] = kvp[1]
		}
	}
	
	return info
}
</pre></code>

where str is the result of a call to <pre><code>redis.String((cxn.Do("INFO","all")))</pre></code> with or without section identification as a second argument to the INFO call.

**Comment by therealbill** [comment]
@DevMH or even quicker and less dirty: use https://github.com/therealbill/libredis/tree/master/info which has been in use for a couple of years and has not been brittle in the least.
