### ISSUE TITLE
TLS support

### ISSUE THREAD

**Issue by uhoh-itsmaciek** [garyburd/redigo#99]
There's some movement to [add TLS support to mainline Redis](https://github.com/antirez/redis/issues/2178) now. Since this basically just layers the existing protocol on top of TLS (e.g., see [a Ruby client patch](https://github.com/redis/redis-rb/pull/419/files#diff-20ca4377c0eb8c090a4e21893b08e8f9R216)), I think one can already use redigo with this by passing in a custom dialer, but it might be nice to have better out-of-the-box support. Any thoughts on whether this is a good idea, and if so, what it should look like? Perhaps a `redis.DialTLS`?

**Comment by garyburd** [comment]
I'll add the feature soon after antirez commits the change. The API will look like http.Transport.

**Comment by uhoh-itsmaciek** [comment]
Awesome! Thank you.

**Comment by garyburd** [comment]
Fixed in #186.
